/*
 * Busqueda.java
 *
 * Created on August 23, 2012, 6:37 PM
 */

package mapa_cubacel;

//import com.mysql.jdbc.ResultSet;
//import com.mysql.jdbc.Statement;
import java.sql.Connection;
import java.sql.DriverManager;
import java.sql.SQLException;
import java.sql.Statement;
import javax.naming.spi.DirStateFactory.Result;
import javax.swing.JComboBox;
import javax.swing.JFrame;
import javax.swing.JOptionPane;
//import org.jvnet.substance.*;
//import org.jvnet.substance.watermark.*;


/**
 *
 * @author  kevin
 */
public class Buscador extends javax.swing.JFrame {
    private int select=0;
    java.sql.ResultSet rs1;
    java.sql.ResultSet rs;
    java.sql.ResultSet rs3;
   
    //ResultSet rs;
  private   Connection con = null; 
  private  Statement st = null;
  public String tabla=null;//para las tablas
   public String tabla1=null;
   String cell=null;
   String []r=new String[4];
   String []cont_fecha=new String[4];
   String []cont_recor=new String[4];
   String []cont_flujo=new String[4];
   String []cont_asunt0=new String[4];
   String []cont_ot=new String[4];
   String cont=null;
    private String result;
     int tip;
     int veces=0;
     int elija;
    String index,valor,valor1,valor2,valor3;
     String board,frame,port,slot,org,org1,org2;
     String dev1,dev2;
    String[] val=new String[38900];
    int y=0;
    String nombre_nodo;
    //private ResultSet rs;
    String [] fila=new String[10];
    int aa=0;
    
    /** Creates new form Busqueda */
    public Buscador() {
        initComponents();
    }

    /** This method is called from within the constructor to
     * initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is
     * always regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        buttonGroup1 = new javax.swing.ButtonGroup();
        jPanel1 = new javax.swing.JPanel();
        jPanel3 = new javax.swing.JPanel();
        MsoftHabana = new javax.swing.JRadioButton();
        MsoftJaguey = new javax.swing.JRadioButton();
        MsoftCamaguey = new javax.swing.JRadioButton();
        jPanel4 = new javax.swing.JPanel();
        MSCCubanacan = new javax.swing.JRadioButton();
        jPanel5 = new javax.swing.JPanel();
        BSCCubanacan = new javax.swing.JRadioButton();
        BSCPanorama = new javax.swing.JRadioButton();
        BSCZTE = new javax.swing.JRadioButton();
        BSCJaguey = new javax.swing.JRadioButton();
        BSCVClara = new javax.swing.JRadioButton();
        BSCCamaguey = new javax.swing.JRadioButton();
        BSCHolguin = new javax.swing.JRadioButton();
        jPanel11 = new javax.swing.JPanel();
        jPanel2 = new javax.swing.JPanel();
        jPanel9 = new javax.swing.JPanel();
        Fj = new javax.swing.JRadioButton();
        Fecha = new javax.swing.JRadioButton();
        OT = new javax.swing.JRadioButton();
        DestinoFJ = new javax.swing.JComboBox();
        ContBusqueda = new javax.swing.JTextField();
        jLabel13 = new javax.swing.JLabel();
        jLabel12 = new javax.swing.JLabel();
        Cantidad = new javax.swing.JTextField();
        Buscar3 = new javax.swing.JButton();
        jPanel10 = new javax.swing.JPanel();
        jScrollPane1 = new javax.swing.JScrollPane();
        Asunto = new javax.swing.JTextArea();
        jScrollPane2 = new javax.swing.JScrollPane();
        Recorrido = new javax.swing.JTextArea();
        FJtext = new javax.swing.JTextField();
        FechaText = new javax.swing.JTextField();
        OTText = new javax.swing.JTextField();
        jLabel14 = new javax.swing.JLabel();
        jLabel15 = new javax.swing.JLabel();
        jLabel16 = new javax.swing.JLabel();
        jLabel17 = new javax.swing.JLabel();
        jLabel18 = new javax.swing.JLabel();
        jPanel6 = new javax.swing.JPanel();
        jPanel8 = new javax.swing.JPanel();
        Dip = new javax.swing.JTextField();
        Celdas = new javax.swing.JTextField();
        DestinoBSC = new javax.swing.JTextField();
        Elija = new javax.swing.JCheckBox();
        Device = new javax.swing.JComboBox();
        Buscar2 = new javax.swing.JButton();
        jLabel11 = new javax.swing.JLabel();
        jLabel10 = new javax.swing.JLabel();
        jLabel9 = new javax.swing.JLabel();
        jLabel8 = new javax.swing.JLabel();
        TG = new javax.swing.JTextField();
        Elija1 = new javax.swing.JCheckBox();
        jLabel19 = new javax.swing.JLabel();
        jPanel7 = new javax.swing.JPanel();
        BoardType = new javax.swing.JComboBox();
        DestinoMsot = new javax.swing.JTextField();
        TID = new javax.swing.JTextField();
        Buscar1 = new javax.swing.JButton();
        jLabel1 = new javax.swing.JLabel();
        jSpinner1 = new javax.swing.JSpinner();
        jSpinner2 = new javax.swing.JSpinner();
        jSpinner3 = new javax.swing.JSpinner();
        jSpinner4 = new javax.swing.JSpinner();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        jLabel6 = new javax.swing.JLabel();
        jLabel7 = new javax.swing.JLabel();
        jButton1 = new javax.swing.JButton();
        Entrar = new javax.swing.JTextField();
        jLabel20 = new javax.swing.JLabel();
        Mostrar = new javax.swing.JTextField();

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);
        setMinimumSize(new java.awt.Dimension(1000, 600));
        setResizable(false);

        jPanel1.setBackground(new java.awt.Color(51, 51, 255));
        jPanel1.setMinimumSize(new java.awt.Dimension(200, 600));
        jPanel1.setPreferredSize(new java.awt.Dimension(200, 600));

        jPanel3.setBorder(javax.swing.BorderFactory.createTitledBorder("MSoft"));
        jPanel3.setPreferredSize(new java.awt.Dimension(200, 180));
        jPanel3.setLayout(new javax.swing.BoxLayout(jPanel3, javax.swing.BoxLayout.Y_AXIS));

        MsoftHabana.setText("Habana");
        MsoftHabana.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                MsoftHabanaActionPerformed(evt);
            }
        });
        jPanel3.add(MsoftHabana);

        MsoftJaguey.setText("Jaguey");
        MsoftJaguey.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                MsoftJagueyActionPerformed(evt);
            }
        });
        jPanel3.add(MsoftJaguey);

        MsoftCamaguey.setText("Camaguey");
        MsoftCamaguey.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                MsoftCamagueyActionPerformed(evt);
            }
        });
        jPanel3.add(MsoftCamaguey);

        jPanel1.add(jPanel3);

        jPanel4.setBorder(javax.swing.BorderFactory.createTitledBorder("MSC"));
        jPanel4.setPreferredSize(new java.awt.Dimension(200, 90));
        jPanel4.setLayout(new javax.swing.BoxLayout(jPanel4, javax.swing.BoxLayout.Y_AXIS));

        MSCCubanacan.setText("Cuabanacan");
        MSCCubanacan.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                MSCCubanacanActionPerformed(evt);
            }
        });
        jPanel4.add(MSCCubanacan);

        jPanel1.add(jPanel4);

        jPanel5.setBorder(javax.swing.BorderFactory.createTitledBorder("BSC"));
        jPanel5.setPreferredSize(new java.awt.Dimension(200, 220));
        jPanel5.setLayout(new javax.swing.BoxLayout(jPanel5, javax.swing.BoxLayout.Y_AXIS));

        BSCCubanacan.setText("Cubanacan");
        BSCCubanacan.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                BSCCubanacanActionPerformed(evt);
            }
        });
        jPanel5.add(BSCCubanacan);

        BSCPanorama.setText("Panorama");
        BSCPanorama.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                BSCPanoramaActionPerformed(evt);
            }
        });
        jPanel5.add(BSCPanorama);

        BSCZTE.setText("ZTE");
        BSCZTE.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                BSCZTEActionPerformed(evt);
            }
        });
        jPanel5.add(BSCZTE);

        BSCJaguey.setText("Jaguey");
        BSCJaguey.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                BSCJagueyActionPerformed(evt);
            }
        });
        jPanel5.add(BSCJaguey);

        BSCVClara.setText("VClara");
        BSCVClara.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                BSCVClaraActionPerformed(evt);
            }
        });
        jPanel5.add(BSCVClara);

        BSCCamaguey.setText("Camaguey");
        BSCCamaguey.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                BSCCamagueyActionPerformed(evt);
            }
        });
        jPanel5.add(BSCCamaguey);

        BSCHolguin.setText("Holguin");
        BSCHolguin.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                BSCHolguinActionPerformed(evt);
            }
        });
        jPanel5.add(BSCHolguin);

        jPanel1.add(jPanel5);

        jPanel11.setPreferredSize(new java.awt.Dimension(200, 100));

        javax.swing.GroupLayout jPanel11Layout = new javax.swing.GroupLayout(jPanel11);
        jPanel11.setLayout(jPanel11Layout);
        jPanel11Layout.setHorizontalGroup(
            jPanel11Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 200, Short.MAX_VALUE)
        );
        jPanel11Layout.setVerticalGroup(
            jPanel11Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 100, Short.MAX_VALUE)
        );

        jPanel1.add(jPanel11);

        getContentPane().add(jPanel1, java.awt.BorderLayout.WEST);

        jPanel2.setMinimumSize(new java.awt.Dimension(400, 600));
        jPanel2.setPreferredSize(new java.awt.Dimension(400, 600));
        jPanel2.setLayout(new java.awt.BorderLayout());

        jPanel9.setBorder(javax.swing.BorderFactory.createEtchedBorder());
        jPanel9.setPreferredSize(new java.awt.Dimension(400, 300));

        Fj.setText("Fj");
        Fj.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                FjActionPerformed(evt);
            }
        });

        Fecha.setText("Fecha");
        Fecha.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                FechaActionPerformed(evt);
            }
        });

        OT.setText("Orden de Trabajo");
        OT.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                OTActionPerformed(evt);
            }
        });

        DestinoFJ.setEnabled(false);
        DestinoFJ.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                DestinoFJActionPerformed(evt);
            }
        });

        ContBusqueda.setEnabled(false);

        jLabel13.setText("Contenido de busqueda");

        jLabel12.setText("Destino");

        Buscar3.setText("Buscar");
        Buscar3.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                Buscar3ActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel9Layout = new javax.swing.GroupLayout(jPanel9);
        jPanel9.setLayout(jPanel9Layout);
        jPanel9Layout.setHorizontalGroup(
            jPanel9Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel9Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel9Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel9Layout.createSequentialGroup()
                        .addGroup(jPanel9Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                            .addComponent(DestinoFJ, javax.swing.GroupLayout.Alignment.LEADING, 0, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(OT, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 164, Short.MAX_VALUE)
                        .addComponent(Cantidad, javax.swing.GroupLayout.PREFERRED_SIZE, 17, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(94, 94, 94))
                    .addGroup(jPanel9Layout.createSequentialGroup()
                        .addGroup(jPanel9Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(Fj)
                            .addComponent(jLabel12))
                        .addContainerGap(350, Short.MAX_VALUE))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel9Layout.createSequentialGroup()
                        .addGroup(jPanel9Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addComponent(jLabel13)
                            .addGroup(jPanel9Layout.createSequentialGroup()
                                .addComponent(Fecha)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 40, Short.MAX_VALUE)
                                .addComponent(ContBusqueda, javax.swing.GroupLayout.PREFERRED_SIZE, 119, javax.swing.GroupLayout.PREFERRED_SIZE)))
                        .addGap(172, 172, 172))))
            .addGroup(jPanel9Layout.createSequentialGroup()
                .addGap(39, 39, 39)
                .addComponent(Buscar3)
                .addContainerGap(290, Short.MAX_VALUE))
        );
        jPanel9Layout.setVerticalGroup(
            jPanel9Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel9Layout.createSequentialGroup()
                .addGroup(jPanel9Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addGroup(jPanel9Layout.createSequentialGroup()
                        .addGap(34, 34, 34)
                        .addComponent(Fj)
                        .addGap(18, 18, 18))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel9Layout.createSequentialGroup()
                        .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(jLabel13)
                        .addGap(7, 7, 7)))
                .addGroup(jPanel9Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(Fecha)
                    .addComponent(ContBusqueda, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addComponent(OT)
                .addGap(22, 22, 22)
                .addComponent(jLabel12)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel9Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(DestinoFJ, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(Cantidad, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(27, 27, 27)
                .addComponent(Buscar3)
                .addContainerGap(45, Short.MAX_VALUE))
        );

        jPanel2.add(jPanel9, java.awt.BorderLayout.NORTH);

        jPanel10.setBorder(javax.swing.BorderFactory.createEtchedBorder());
        jPanel10.setPreferredSize(new java.awt.Dimension(400, 300));

        Asunto.setColumns(20);
        Asunto.setRows(5);
        Asunto.setEnabled(false);
        jScrollPane1.setViewportView(Asunto);

        Recorrido.setColumns(20);
        Recorrido.setFont(new java.awt.Font("Arial", 0, 14)); // NOI18N
        Recorrido.setRows(6);
        Recorrido.setEnabled(false);
        jScrollPane2.setViewportView(Recorrido);

        FJtext.setEnabled(false);

        FechaText.setEnabled(false);

        OTText.setEnabled(false);

        jLabel14.setText("Fj");

        jLabel15.setText("Fecha");

        jLabel16.setText("Orden de trabajo");

        jLabel17.setText("Asunto");

        jLabel18.setText("Recorrido");

        javax.swing.GroupLayout jPanel10Layout = new javax.swing.GroupLayout(jPanel10);
        jPanel10.setLayout(jPanel10Layout);
        jPanel10Layout.setHorizontalGroup(
            jPanel10Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel10Layout.createSequentialGroup()
                .addGroup(jPanel10Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel10Layout.createSequentialGroup()
                        .addGap(26, 26, 26)
                        .addGroup(jPanel10Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel14)
                            .addComponent(FJtext, javax.swing.GroupLayout.PREFERRED_SIZE, 63, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(27, 27, 27)
                        .addGroup(jPanel10Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel15)
                            .addComponent(FechaText, javax.swing.GroupLayout.PREFERRED_SIZE, 71, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(34, 34, 34)
                        .addGroup(jPanel10Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel16)
                            .addComponent(OTText, javax.swing.GroupLayout.PREFERRED_SIZE, 71, javax.swing.GroupLayout.PREFERRED_SIZE)))
                    .addGroup(jPanel10Layout.createSequentialGroup()
                        .addGap(88, 88, 88)
                        .addComponent(jLabel17))
                    .addGroup(jPanel10Layout.createSequentialGroup()
                        .addGap(92, 92, 92)
                        .addComponent(jLabel18))
                    .addGroup(jPanel10Layout.createSequentialGroup()
                        .addContainerGap()
                        .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 292, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(jPanel10Layout.createSequentialGroup()
                        .addContainerGap()
                        .addComponent(jScrollPane2, javax.swing.GroupLayout.PREFERRED_SIZE, 320, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addGap(66, 66, 66))
        );
        jPanel10Layout.setVerticalGroup(
            jPanel10Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel10Layout.createSequentialGroup()
                .addGap(19, 19, 19)
                .addGroup(jPanel10Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel14)
                    .addComponent(jLabel16)
                    .addComponent(jLabel15))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel10Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(OTText, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(FechaText, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(FJtext, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 25, Short.MAX_VALUE)
                .addComponent(jLabel17)
                .addGap(1, 1, 1)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 72, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(jLabel18)
                .addGap(3, 3, 3)
                .addComponent(jScrollPane2, javax.swing.GroupLayout.PREFERRED_SIZE, 86, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap())
        );

        jPanel2.add(jPanel10, java.awt.BorderLayout.SOUTH);

        getContentPane().add(jPanel2, java.awt.BorderLayout.EAST);

        jPanel6.setBackground(new java.awt.Color(255, 255, 204));
        jPanel6.setMinimumSize(new java.awt.Dimension(400, 600));
        jPanel6.setPreferredSize(new java.awt.Dimension(400, 600));
        jPanel6.setLayout(new java.awt.BorderLayout());

        jPanel8.setMinimumSize(new java.awt.Dimension(300, 300));
        jPanel8.setPreferredSize(new java.awt.Dimension(300, 300));

        Dip.setEnabled(false);

        Celdas.setEnabled(false);

        DestinoBSC.setEnabled(false);
        DestinoBSC.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                DestinoBSCActionPerformed(evt);
            }
        });

        Elija.setText("Elija");
        Elija.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                ElijaActionPerformed(evt);
            }
        });

        Device.setModel(new javax.swing.DefaultComboBoxModel(new String[] { "", "Item 1", "Item 2", "Item 3", "Item 4" }));
        Device.setEnabled(false);
        Device.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                DeviceActionPerformed(evt);
            }
        });

        Buscar2.setText("Buscar");
        Buscar2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                Buscar2ActionPerformed(evt);
            }
        });

        jLabel11.setText("Destino");

        jLabel10.setText("Celdas");

        jLabel9.setText("Dip");

        jLabel8.setText("Device");

        TG.setEnabled(false);

        Elija1.setText("Elija");
        Elija1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                Elija1ActionPerformed(evt);
            }
        });

        jLabel19.setText("TG");

        jPanel7.setMinimumSize(new java.awt.Dimension(300, 300));
        jPanel7.setPreferredSize(new java.awt.Dimension(300, 300));

        BoardType.setModel(new javax.swing.DefaultComboBoxModel(new String[] { "E32", "S2L" }));
        BoardType.setEnabled(false);
        BoardType.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                BoardTypeActionPerformed(evt);
            }
        });

        DestinoMsot.setEnabled(false);

        TID.setEnabled(false);

        Buscar1.setText("Buscar");
        Buscar1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                Buscar1ActionPerformed(evt);
            }
        });

        jLabel1.setText("Board Type");

        jSpinner1.setEnabled(false);

        jSpinner2.setEnabled(false);

        jSpinner3.setEnabled(false);

        jSpinner4.setEnabled(false);

        jLabel2.setText("Board");

        jLabel3.setText("Port");

        jLabel4.setText("Frame");

        jLabel5.setText("Slot");

        jLabel6.setText("Destino");

        jLabel7.setText("TID");

        jButton1.setText("jButton1");
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });

        Entrar.setMinimumSize(new java.awt.Dimension(88, 88));
        Entrar.setPreferredSize(new java.awt.Dimension(16, 20));
        Entrar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                EntrarActionPerformed(evt);
            }
        });

        jLabel20.setText("Entre numero");

        javax.swing.GroupLayout jPanel7Layout = new javax.swing.GroupLayout(jPanel7);
        jPanel7.setLayout(jPanel7Layout);
        jPanel7Layout.setHorizontalGroup(
            jPanel7Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel7Layout.createSequentialGroup()
                .addGroup(jPanel7Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel7Layout.createSequentialGroup()
                        .addGap(27, 27, 27)
                        .addComponent(Buscar1))
                    .addGroup(jPanel7Layout.createSequentialGroup()
                        .addContainerGap()
                        .addGroup(jPanel7Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                            .addGroup(javax.swing.GroupLayout.Alignment.LEADING, jPanel7Layout.createSequentialGroup()
                                .addGap(25, 25, 25)
                                .addComponent(jLabel6))
                            .addComponent(DestinoMsot, javax.swing.GroupLayout.PREFERRED_SIZE, 109, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(29, 29, 29)
                        .addGroup(jPanel7Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel7)
                            .addComponent(TID, javax.swing.GroupLayout.PREFERRED_SIZE, 59, javax.swing.GroupLayout.PREFERRED_SIZE)))
                    .addGroup(jPanel7Layout.createSequentialGroup()
                        .addGap(35, 35, 35)
                        .addGroup(jPanel7Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addGroup(jPanel7Layout.createSequentialGroup()
                                .addGroup(jPanel7Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(BoardType, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(jLabel1))
                                .addGap(31, 31, 31)
                                .addGroup(jPanel7Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(jSpinner1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(jLabel2))
                                .addGap(37, 37, 37)
                                .addGroup(jPanel7Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                                    .addComponent(jSpinner3, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(jLabel4))
                                .addGap(18, 18, 18)
                                .addGroup(jPanel7Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(jSpinner4, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(jLabel5))
                                .addGap(18, 18, 18)
                                .addGroup(jPanel7Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(jSpinner2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(jLabel3)))
                            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel7Layout.createSequentialGroup()
                                .addComponent(jButton1)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 170, Short.MAX_VALUE)
                                .addGroup(jPanel7Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(Entrar, javax.swing.GroupLayout.PREFERRED_SIZE, 80, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(Mostrar, javax.swing.GroupLayout.PREFERRED_SIZE, 106, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(jLabel20))))))
                .addContainerGap(118, Short.MAX_VALUE))
        );
        jPanel7Layout.setVerticalGroup(
            jPanel7Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel7Layout.createSequentialGroup()
                .addGroup(jPanel7Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel7Layout.createSequentialGroup()
                        .addGroup(jPanel7Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(jPanel7Layout.createSequentialGroup()
                                .addGap(9, 9, 9)
                                .addComponent(jLabel1)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(BoardType, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addGroup(jPanel7Layout.createSequentialGroup()
                                .addContainerGap()
                                .addComponent(jLabel2)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(jSpinner1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
                        .addGap(33, 33, 33)
                        .addGroup(jPanel7Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addGroup(jPanel7Layout.createSequentialGroup()
                                .addComponent(jLabel6)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(DestinoMsot, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addGroup(jPanel7Layout.createSequentialGroup()
                                .addComponent(jLabel7)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(TID, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
                        .addGap(27, 27, 27)
                        .addComponent(Buscar1))
                    .addGroup(jPanel7Layout.createSequentialGroup()
                        .addContainerGap()
                        .addGroup(jPanel7Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addGroup(jPanel7Layout.createSequentialGroup()
                                .addComponent(jLabel5)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(jSpinner4, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addGroup(jPanel7Layout.createSequentialGroup()
                                .addComponent(jLabel4)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(jSpinner3, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addGroup(jPanel7Layout.createSequentialGroup()
                                .addComponent(jLabel3)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(jSpinner2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 40, Short.MAX_VALUE)
                .addComponent(jLabel20)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel7Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jButton1)
                    .addComponent(Entrar, javax.swing.GroupLayout.PREFERRED_SIZE, 20, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(Mostrar, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(17, 17, 17))
        );

        javax.swing.GroupLayout jPanel8Layout = new javax.swing.GroupLayout(jPanel8);
        jPanel8.setLayout(jPanel8Layout);
        jPanel8Layout.setHorizontalGroup(
            jPanel8Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel8Layout.createSequentialGroup()
                .addGap(56, 56, 56)
                .addGroup(jPanel8Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(Buscar2)
                    .addComponent(jLabel11)
                    .addComponent(DestinoBSC, javax.swing.GroupLayout.PREFERRED_SIZE, 136, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGroup(jPanel8Layout.createSequentialGroup()
                        .addGroup(jPanel8Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(Dip, javax.swing.GroupLayout.PREFERRED_SIZE, 40, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jLabel9))
                        .addGap(31, 31, 31)
                        .addGroup(jPanel8Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel8)
                            .addComponent(Device, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))))
                .addGroup(jPanel8Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel8Layout.createSequentialGroup()
                        .addGap(34, 34, 34)
                        .addComponent(jLabel10))
                    .addGroup(jPanel8Layout.createSequentialGroup()
                        .addGap(22, 22, 22)
                        .addGroup(jPanel8Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel19)
                            .addGroup(jPanel8Layout.createSequentialGroup()
                                .addGroup(jPanel8Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(Celdas, javax.swing.GroupLayout.PREFERRED_SIZE, 66, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(TG, javax.swing.GroupLayout.PREFERRED_SIZE, 34, javax.swing.GroupLayout.PREFERRED_SIZE))
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addGroup(jPanel8Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(Elija1)
                                    .addComponent(Elija))))))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel8Layout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(jPanel7, javax.swing.GroupLayout.PREFERRED_SIZE, 502, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap())
        );
        jPanel8Layout.setVerticalGroup(
            jPanel8Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel8Layout.createSequentialGroup()
                .addContainerGap(23, Short.MAX_VALUE)
                .addComponent(jPanel7, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(jPanel8Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel9)
                    .addComponent(jLabel8)
                    .addComponent(jLabel10))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel8Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(Dip, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(Device, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(Celdas, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(Elija))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jLabel19)
                .addGap(7, 7, 7)
                .addGroup(jPanel8Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(TG, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(Elija1))
                .addGap(34, 34, 34)
                .addComponent(jLabel11)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(DestinoBSC, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(38, 38, 38)
                .addComponent(Buscar2)
                .addGap(41, 41, 41))
        );

        jPanel6.add(jPanel8, java.awt.BorderLayout.CENTER);

        getContentPane().add(jPanel6, java.awt.BorderLayout.CENTER);

        pack();
    }// </editor-fold>//GEN-END:initComponents

private void MsoftJagueyActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_MsoftJagueyActionPerformed
// TODO add your handling code here:
    y=2;
    MsoftCamaguey.setSelected(false);
    MsoftHabana.setSelected(false);
    MSCCubanacan.setSelected(false);
    BSCPanorama.setSelected(false);
    BSCZTE.setSelected(false);
    BSCJaguey.setSelected(false);
    BSCVClara.setSelected(false);
    BSCCamaguey.setSelected(false);
    BSCHolguin.setSelected(false);
    BSCCubanacan.setSelected(false);
    BoardType.setEnabled(true);
    Dip.setText(" ");
    Dip.setEnabled(false);
    //jComboBox2.setSelectedIndex(0);
    Device.setEnabled(false);
    DestinoMsot.setText(" ");
    Asunto.setText(" ");
    Recorrido.setText(" ");
    Fj.setSelected(false);
    OT.setSelected(false);
    Fecha.setSelected(false);
    ContBusqueda.setEnabled(false);
    FJtext.setText(" ");
    FechaText.setText(" ");
    OTText.setText(" ");
    ContBusqueda.setText(" ");
    
    //jComboBox2.setSelectedIndex(0);
    tip=0;
    org="tb_rutas_msfjaguey";//MsofJaguey
}//GEN-LAST:event_MsoftJagueyActionPerformed

private void BSCPanoramaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_BSCPanoramaActionPerformed
// TODO add your handling code here:
    y=0;//Para saber que esta desactivado los MSoft
    MsoftHabana.setSelected(false);
    MsoftJaguey.setSelected(false);
    MsoftCamaguey.setSelected(false);
    MSCCubanacan.setSelected(false);
    BSCZTE.setSelected(false);
    BSCJaguey.setSelected(false);
    BSCVClara.setSelected(false);
    BSCCamaguey.setSelected(false);
    BSCHolguin.setSelected(false);
    BSCCubanacan.setSelected(false);
    BoardType.setEnabled(false);
    DestinoFJ.setEnabled(false);
    DestinoFJ.removeAllItems();
    FJtext.setEnabled(true);
    FechaText.setEnabled(true);
    OTText.setEnabled(true);
    Asunto.setEnabled(true);
    Recorrido.setEnabled(true);
    Dip.setText(" ");
    Dip.setEnabled(false);
    BSCPanorama.setSelected(true);
    Device.setEnabled(true);
    Dip.setEnabled(true);
    Asunto.setText(" ");
    Recorrido.setText(" ");
    Fj.setSelected(false);
    OT.setSelected(false);
    Fecha.setSelected(false);
    ContBusqueda.setEnabled(false);
   String list[]={"","RBL2"};
    JComboBox cb=new JComboBox(list);
    Device.setModel(cb.getModel());
    FJtext.setText(" ");
    FechaText.setText(" ");
    OTText.setText(" ");
    ContBusqueda.setText(" ");
    tip=2;
    org="tb_bsc_pan";//dice el nodo a buscar
    org1="tb_cell_pan";
    nombre_nodo="BSC PANORAMA";
    aa=0;//para que no se levante el DeviceFJ
    Cantidad.setText(" ");
    veces=0;
    Elija.setSelected(false);
    Elija1.setSelected(false);
      Celdas.setText(" ");
    DestinoBSC.setText(" ");
    TG.setEnabled(false);
    TG.setText(" ");TG.setEnabled(false);
    TG.setText(" ");
    try{
            Class.forName("com.mysql.jdbc.Driver"); // 2005 version
            con = DriverManager.getConnection("jdbc:mysql://10.94.1.143:3306/gestion_trafico","etecsa","etecsa");
            java.sql.Statement  st = con.createStatement();
            String strSQL="Select distinct rsite from "+org+" group by rsite";
            rs =st.executeQuery(strSQL); 
                
           DestinoFJ.setEnabled(true);
                 while (rs.next()) 
                 {
                    
                         DestinoFJ.addItem(rs.getObject("rsite") );      
                                 
                      

                 }
                  
                   //Muestra la ruta independientemente del tipo de nodo
                   valor=" ";
                   valor1=" ";


                   rs.close();           
                   st.close(); 
                   con.close();

                       
}
    
catch ( SQLException excepcionSql)
{ 
JOptionPane.showMessageDialog( null, excepcionSql.getMessage(),"Error en base de datos", JOptionPane.ERROR_MESSAGE );
}

//errores con la carga del controlador de la base de datos(Driver)

catch ( ClassNotFoundException claseNoEncontrada ){
JOptionPane.showMessageDialog( null, claseNoEncontrada.getMessage(),"No se encontró el controlador", JOptionPane.ERROR_MESSAGE );
} 
    
}//GEN-LAST:event_BSCPanoramaActionPerformed

private void BSCHolguinActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_BSCHolguinActionPerformed
// TODO add your handling code here:
    y=0;//Para saber que esta desactivado los MSoft
    MsoftHabana.setSelected(false);
    MsoftJaguey.setSelected(false);
    MsoftCamaguey.setSelected(false);
    MSCCubanacan.setSelected(false);
    BSCPanorama.setSelected(false);
    BSCZTE.setSelected(false);
    BSCJaguey.setSelected(false);
    BSCVClara.setSelected(false);
    BSCCamaguey.setSelected(false);
    //BSCHolguin.setSelected(false);
    BSCCubanacan.setSelected(false);
    BoardType.setEnabled(false);
    DestinoFJ.setEnabled(false);
    DestinoFJ.removeAllItems();
    FJtext.setEnabled(true);
    FechaText.setEnabled(true);
    OTText.setEnabled(true);
    Asunto.setEnabled(true);
    Recorrido.setEnabled(true);
    Dip.setText(" ");
    Dip.setEnabled(false);
    DestinoFJ.setEnabled(true);
    BSCHolguin.setSelected(true);
    Device.setEnabled(true);
    Dip.setEnabled(true);
    Asunto.setText(" ");
    Recorrido.setText(" ");
    Fj.setSelected(false);
    OT.setSelected(false);
    Fecha.setSelected(false);
    ContBusqueda.setEnabled(false);
    FJtext.setText(" ");
    FechaText.setText(" ");
    OTText.setText(" ");
    ContBusqueda.setText(" ");
    aa=0;//para que no se levante el DeviceFJ
   //String list[]={"","RBL2"};
    //JComboBox cb=new JComboBox(list);
    //Device.setModel(cb.getModel());
    tip=2;
    org="tb_cell_cam";//dice el nodo a buscar
    org1="null";
    nombre_nodo="BSC HOLGUIN";
    Cantidad.setText(" "); Cantidad.setText(" ");//Pone vacio la cantidad de ocurrencia
    veces=0;
    Elija.setSelected(false);
    Elija1.setSelected(false);
    Celdas.setText(" ");
    DestinoBSC.setText(" ");
    TG.setEnabled(false);
    TG.setText(" ");
    try{
            Class.forName("com.mysql.jdbc.Driver"); // 2005 version
            con = DriverManager.getConnection("jdbc:mysql://10.94.1.143:3306/gestion_trafico","etecsa","etecsa");
            java.sql.Statement  st = con.createStatement();
            String strSQL="Select distinct rsite from "+org+" where id_bsc=11  group by rsite";
            rs =st.executeQuery(strSQL); 
                
           DestinoFJ.setEnabled(true);
                 while (rs.next()) 
                 {
                    
                         DestinoFJ.addItem(rs.getObject("rsite") );      
                                 
                      

                 }
                  
                   //Muestra la ruta independientemente del tipo de nodo
                   valor=" ";
                   valor1=" ";


                   rs.close();           
                   st.close(); 
                   con.close();

                       
}
    
catch ( SQLException excepcionSql)
{ 
JOptionPane.showMessageDialog( null, excepcionSql.getMessage(),"Error en base de datos", JOptionPane.ERROR_MESSAGE );
}

//errores con la carga del controlador de la base de datos(Driver)

catch ( ClassNotFoundException claseNoEncontrada ){
JOptionPane.showMessageDialog( null, claseNoEncontrada.getMessage(),"No se encontró el controlador", JOptionPane.ERROR_MESSAGE );
} 
}//GEN-LAST:event_BSCHolguinActionPerformed

private void MsoftCamagueyActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_MsoftCamagueyActionPerformed
// TODO add your handling code here:
    y=3;
    MsoftHabana.setSelected(false);
    MsoftJaguey.setSelected(false);
    MSCCubanacan.setSelected(false);
    BSCPanorama.setSelected(false);
    BSCZTE.setSelected(false);
    BSCJaguey.setSelected(false);
    BSCVClara.setSelected(false);
    BSCCamaguey.setSelected(false);
    BSCHolguin.setSelected(false);
    BSCCubanacan.setSelected(false);
    BoardType.setEnabled(true);
    Dip.setText(" ");
    Dip.setEnabled(false);
    //jComboBox2.setSelectedIndex(0);
    Device.setEnabled(false);
    DestinoMsot.setText(" ");
    Asunto.setText(" ");
    Recorrido.setText(" ");
    Fj.setSelected(false);
    OT.setSelected(false);
    Fecha.setSelected(false);
    ContBusqueda.setEnabled(false);
    FJtext.setText(" ");
    FechaText.setText(" ");
    OTText.setText(" ");
    ContBusqueda.setText(" ");
    tip=0;
    org="tb_rutas_msfcam"; //MsoftCamaguey
}//GEN-LAST:event_MsoftCamagueyActionPerformed

private void DestinoBSCActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_DestinoBSCActionPerformed
// TODO add your handling code here:
}//GEN-LAST:event_DestinoBSCActionPerformed

private void MSCCubanacanActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_MSCCubanacanActionPerformed
// TODO add your handling code here:
    y=4;
    MsoftHabana.setSelected(false);
    MsoftJaguey.setSelected(false);
    MSCCubanacan.setSelected(true);
    BSCPanorama.setSelected(false);
    BSCZTE.setSelected(false);
    BSCJaguey.setSelected(false);
    BSCVClara.setSelected(false);
    BSCCamaguey.setSelected(false);
    BSCHolguin.setSelected(false);
    BSCCubanacan.setSelected(false);
    BoardType.setEnabled(true);
    Dip.setText(" ");
    Dip.setEnabled(true);
    Device.setEnabled(true);
    Asunto.setText(" ");
    Recorrido.setText(" ");
    Fj.setSelected(false);
    OT.setSelected(false);
    Fecha.setSelected(false);
    ContBusqueda.setEnabled(false);
    FJtext.setText(" ");
    FechaText.setText(" ");
    OTText.setText(" ");
    ContBusqueda.setText(" ");
    Elija.setSelected(false);
    Elija1.setSelected(false);
    TG.setText(" ");
    TG.setEnabled(false);
    DestinoBSC.setText(" ");
    DestinoBSC.setEnabled(false);
    DestinoFJ.setEnabled(false);
    DestinoFJ.removeAllItems();
    //jComboBox2.setSelectedIndex(0);
     elija=5;
    String list[]={"LPRAGS","MAL1","MALT","UPD","UPD1"};
    JComboBox cb=new JComboBox(list);
    Device.setModel(cb.getModel());
    tip=1;
    org="tb_dev_msc_prueba";//MSC Cubanacan
}//GEN-LAST:event_MSCCubanacanActionPerformed

private void MsoftHabanaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_MsoftHabanaActionPerformed
// TODO add your handling code here:
    y=1;
    MsoftJaguey.setSelected(false);
    MSCCubanacan.setSelected(false);
    MsoftCamaguey.setSelected(false);
    BSCPanorama.setSelected(false);
    BSCZTE.setSelected(false);
    BSCJaguey.setSelected(false);
    BSCVClara.setSelected(false);
    BSCCamaguey.setSelected(false);
    BSCHolguin.setSelected(false);
    BSCCubanacan.setSelected(false);
    BoardType.setEnabled(true);
    Dip.setText(" ");
    Dip.setEnabled(false);
    Asunto.setText(" ");
    Recorrido.setText(" ");
    Fj.setSelected(false);
    OT.setSelected(false);
    Fecha.setSelected(false);
    ContBusqueda.setEnabled(false);
    FJtext.setText(" ");
    FechaText.setText(" ");
    OTText.setText(" ");
    ContBusqueda.setText(" ");
    TID.setEnabled(true);
    //jComboBox2.setSelectedIndex();
    
    tip=0;
    org="tb_rutas_msfhab";//MsoftHabana
}//GEN-LAST:event_MsoftHabanaActionPerformed

private void BoardTypeActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_BoardTypeActionPerformed
// TODO add your handling code here:
    index=(String) BoardType.getSelectedItem();// se optine valor seleccionado
    jSpinner1.setEnabled(true);
    jSpinner2.setEnabled(true);
    jSpinner3.setEnabled(true);
    jSpinner4.setEnabled(true);
   
}//GEN-LAST:event_BoardTypeActionPerformed

private void Buscar1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_Buscar1ActionPerformed
// TODO add your handling code here:
    frame= jSpinner3.getValue().toString();
    port= jSpinner2.getValue().toString();
    slot=jSpinner4.getValue().toString();
    board=jSpinner1.getValue().toString();
    
    try{
        Class.forName("com.mysql.jdbc.Driver"); // 2005 version
        con = DriverManager.getConnection("jdbc:mysql://10.94.1.143:3306/gestion_trafico","etecsa","etecsa");
        java.sql.Statement  st = con.createStatement();            
        String strSQL="Select tid_star from tb_tid where ((board_no='"+board+"')  and (slot_no='"+slot+"' ) and (port_no='"+port+"' )and (frame_no='"+frame+"' ) and (board_type='"+BoardType.getSelectedItem()+"'))";
        rs =  st.executeQuery(strSQL); 

                 while (rs.next()) 
                 {
                        
                        valor=rs.getString(1);//tengo valor de tid_start
                        TID.setText(valor);
                  }
                    
              
           
             String strSQL1="Select ruta from "+org+" where tid_star='"+valor+"' ";
              rs1=  st.executeQuery(strSQL1); 
             
                DestinoMsot.setEnabled(true);
                while (rs1.next()) 
                     {
                        valor1=rs1.getString(1);
                 
            DestinoMsot.setText(rs1.getString("ruta"));
            
                     }
            
           
            
           valor=" ";
           valor1=" ";
           
           
           
         rs.close();           
         st.close(); 
         con.close();
    }
    
         catch ( SQLException excepcionSql)
{ 
JOptionPane.showMessageDialog( null, excepcionSql.getMessage(),"Error en base de datos", JOptionPane.ERROR_MESSAGE );
}

//errores con la carga del controlador de la base de datos(Driver)

catch ( ClassNotFoundException claseNoEncontrada ){
JOptionPane.showMessageDialog( null, claseNoEncontrada.getMessage(),"No se encontró el controlador", JOptionPane.ERROR_MESSAGE );
} 
}//GEN-LAST:event_Buscar1ActionPerformed

private void BSCCubanacanActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_BSCCubanacanActionPerformed
// TODO add your handling code here:
    y=0;//Para saber que esta desactivado los MSoft
    MsoftHabana.setSelected(false);
    MsoftJaguey.setSelected(false);
    MsoftCamaguey.setSelected(false);
    MSCCubanacan.setSelected(false);
    BSCPanorama.setSelected(false);
    BSCZTE.setSelected(false);
    BSCJaguey.setSelected(false);
    BSCVClara.setSelected(false);
    BSCCamaguey.setSelected(false);
    BSCHolguin.setSelected(false);
    BSCCubanacan.setSelected(false);
    BoardType.setEnabled(false);
     DestinoFJ.setEnabled(false);
    DestinoFJ.removeAllItems();
    FJtext.setEnabled(true);
    FechaText.setEnabled(true);
    OTText.setEnabled(true);
    Asunto.setEnabled(true);
    Recorrido.setEnabled(true);
    Dip.setText(" ");
    Dip.setEnabled(false);
    BSCCubanacan.setSelected(true);
    Device.setEnabled(true);
    Dip.setEnabled(true);
    Asunto.setText(" ");
    Recorrido.setText(" ");
    FJtext.setText(" ");
    FechaText.setText(" ");
    OTText.setText(" ");
    ContBusqueda.setText(" ");
    Fj.setSelected(false);
    OT.setSelected(false);
    Fecha.setSelected(false);
    ContBusqueda.setEnabled(false);
   String list[]={"","RBL2"};
    JComboBox cb=new JComboBox(list);
    Device.setModel(cb.getModel());
    tip=2;
    org="tb_bsc_cub";//dice el nodo a buscar
    org1="tb_cell_cub";
    nombre_nodo="BSC CUBANACAN";
    aa=0;//para que no se levante el DeviceFJ
   Cantidad.setText(" ");//Pone vacio la cantidad de ocurrencia
    veces=0;
    Elija.setSelected(false);
    Elija1.setSelected(false);
    Celdas.setText(" ");
    DestinoBSC.setText(" ");
    TG.setEnabled(false);
    TG.setText(" ");
    elija=5;
    try{
            Class.forName("com.mysql.jdbc.Driver"); // 2005 version
            con = DriverManager.getConnection("jdbc:mysql://10.94.1.143:3306/gestion_trafico","etecsa","etecsa");
            java.sql.Statement  st = con.createStatement();
            String strSQL="Select rsite from "+org+"  ";
            rs =st.executeQuery(strSQL); 
                
           DestinoFJ.setEnabled(true);
                 while (rs.next()) 
                 {
                    
                         DestinoFJ.addItem(rs.getObject("rsite") );      
                                 
                      

                 }
                  
                   //Muestra la ruta independientemente del tipo de nodo
                   valor=" ";
                   valor1=" ";


                   rs.close();           
                   st.close(); 
                   con.close();

                       
}
    
catch ( SQLException excepcionSql)
{ 
JOptionPane.showMessageDialog( null, excepcionSql.getMessage(),"Error en base de datos", JOptionPane.ERROR_MESSAGE );
}

//errores con la carga del controlador de la base de datos(Driver)

catch ( ClassNotFoundException claseNoEncontrada ){
JOptionPane.showMessageDialog( null, claseNoEncontrada.getMessage(),"No se encontró el controlador", JOptionPane.ERROR_MESSAGE );
} 
    
    
    
}//GEN-LAST:event_BSCCubanacanActionPerformed

private void BSCZTEActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_BSCZTEActionPerformed
// TODO add your handling code here:
    y=0;//Para saber que esta desactivado los MSoft
    MsoftHabana.setSelected(false);
    MsoftJaguey.setSelected(false);
    MsoftCamaguey.setSelected(false);
    MSCCubanacan.setSelected(false);
    BSCPanorama.setSelected(false);
    BSCJaguey.setSelected(false);
    BSCVClara.setSelected(false);
    BSCCamaguey.setSelected(false);
    BSCHolguin.setSelected(false);
    BSCCubanacan.setSelected(false);
    BoardType.setEnabled(false);
    DestinoFJ.setEnabled(true);
    FJtext.setEnabled(true);
    FechaText.setEnabled(true);
    OTText.setEnabled(true);
    Asunto.setEnabled(true);
    Recorrido.setEnabled(true);
    Dip.setText(" ");
    Dip.setEnabled(false);
    BSCZTE.setSelected(true);
    Device.setEnabled(true);
    Dip.setEnabled(true);
    Asunto.setText(" ");
    Recorrido.setText(" ");
    Fj.setSelected(false);
    OT.setSelected(false);
    Fecha.setSelected(false);
    FJtext.setText(" ");
    FechaText.setText(" ");
    OTText.setText(" ");
    ContBusqueda.setText(" ");
    ContBusqueda.setEnabled(false);
    aa=0;//para que no se levante el DeviceFJ
   //String list[]={"","RBL2"};
   // JComboBox cb=new JComboBox(list);
    //Device.setModel(cb.getModel());
    tip=2;
    org="tb_cell_cmg";//dice el nodo a buscar
    org1="tb_cell_zte";
    nombre_nodo="BSC ZTE";
    Cantidad.setText(" "); Cantidad.setText(" ");//Pone vacio la cantidad de ocurrencia
    veces=0;
    Elija.setSelected(false);
    Elija1.setSelected(false);
    Celdas.setText(" ");
    DestinoBSC.setText(" ");
    TG.setEnabled(false);
    TG.setText(" ");
    elija=5;
    try{
            Class.forName("com.mysql.jdbc.Driver"); // 2005 version
            con = DriverManager.getConnection("jdbc:mysql://10.94.1.143:3306/gestion_trafico","etecsa","etecsa");
            java.sql.Statement  st = con.createStatement();
            String strSQL="Select distinct rsite from "+org+" where id_bsc=7  group by rsite ";
            rs =st.executeQuery(strSQL); 
                
           DestinoFJ.setEnabled(true);
                 while (rs.next()) 
                 {
                    
                         DestinoFJ.addItem(rs.getObject("rsite") );      
                                 
                      

                 }
                  
                   //Muestra la ruta independientemente del tipo de nodo
                   valor=" ";
                   valor1=" ";


                   rs.close();           
                   st.close(); 
                   con.close();

                       
}
    
catch ( SQLException excepcionSql)
{ 
JOptionPane.showMessageDialog( null, excepcionSql.getMessage(),"Error en base de datos", JOptionPane.ERROR_MESSAGE );
}

//errores con la carga del controlador de la base de datos(Driver)

catch ( ClassNotFoundException claseNoEncontrada ){
JOptionPane.showMessageDialog( null, claseNoEncontrada.getMessage(),"No se encontró el controlador", JOptionPane.ERROR_MESSAGE );
} 
    
    
}//GEN-LAST:event_BSCZTEActionPerformed

private void BSCJagueyActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_BSCJagueyActionPerformed
// TODO add your handling code here:
    y=0;//Para saber que esta desactivado los MSoft
    MsoftHabana.setSelected(false);
    MsoftJaguey.setSelected(false);
    MsoftCamaguey.setSelected(false);
    MSCCubanacan.setSelected(false);
    BSCPanorama.setSelected(false);
    BSCZTE.setSelected(false);
    //BSCJaguey.setSelected(false);
    BSCVClara.setSelected(false);
    BSCCamaguey.setSelected(false);
    BSCHolguin.setSelected(false);
    BSCCubanacan.setSelected(false);
    BoardType.setEnabled(false);
     DestinoFJ.setEnabled(false);
    DestinoFJ.removeAllItems();
    FJtext.setEnabled(true);
    FechaText.setEnabled(true);
    OTText.setEnabled(true);
    Asunto.setEnabled(true);
    Recorrido.setEnabled(true);
    Dip.setText(" ");
    Dip.setEnabled(false);
    BSCJaguey.setSelected(true);
    DestinoFJ.setEnabled(true);
    Device.setEnabled(true);
    Dip.setEnabled(true);
    Asunto.setText(" ");
    Recorrido.setText(" ");
    Fj.setSelected(false);
    OT.setSelected(false);
    Fecha.setSelected(false);
    ContBusqueda.setEnabled(false);
    FJtext.setText(" ");
    FechaText.setText(" ");
    OTText.setText(" ");
    ContBusqueda.setText(" ");
    aa=0;//para que no se levante el DeviceFJ
    org1=null;
    tip=2;
    org="tb_cell_cam";//dice el nodo a buscar
    nombre_nodo="BSC JAGÜEY GRANDE";
    Cantidad.setText(" "); Cantidad.setText(" ");//Pone vacio la cantidad de ocurrencia
    veces=0;
    Elija.setSelected(false);
    Elija1.setSelected(false);
    Celdas.setText(" ");
    DestinoBSC.setText(" ");
    TG.setEnabled(false);
    TG.setText(" ");
    elija=5;
     try{
            Class.forName("com.mysql.jdbc.Driver"); // 2005 version
            con = DriverManager.getConnection("jdbc:mysql://10.94.1.143:3306/gestion_trafico","etecsa","etecsa");
            java.sql.Statement  st = con.createStatement();
            String strSQL="Select distinct rsite from "+org+" where id_bsc=8  group by rsite ";
            rs =st.executeQuery(strSQL); 
                
           DestinoFJ.setEnabled(true);
                 while (rs.next()) 
                 {
                    
                         DestinoFJ.addItem(rs.getObject("rsite") );      
                                 
                      

                 }
                  
                   //Muestra la ruta independientemente del tipo de nodo
                   valor=" ";
                   valor1=" ";


                   rs.close();           
                   st.close(); 
                   con.close();

                       
}
    
catch ( SQLException excepcionSql)
{ 
JOptionPane.showMessageDialog( null, excepcionSql.getMessage(),"Error en base de datos", JOptionPane.ERROR_MESSAGE );
}

//errores con la carga del controlador de la base de datos(Driver)

catch ( ClassNotFoundException claseNoEncontrada ){
JOptionPane.showMessageDialog( null, claseNoEncontrada.getMessage(),"No se encontró el controlador", JOptionPane.ERROR_MESSAGE );
} 
}//GEN-LAST:event_BSCJagueyActionPerformed

private void BSCVClaraActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_BSCVClaraActionPerformed
// TODO add your handling code here:
    y=0;//Para saber que esta desactivado los MSoft
    MsoftHabana.setSelected(false);
    MsoftJaguey.setSelected(false);
    MsoftCamaguey.setSelected(false);
    MSCCubanacan.setSelected(false);
    BSCPanorama.setSelected(false);
    BSCZTE.setSelected(false);
    BSCJaguey.setSelected(false);
    //BSCVClara.setSelected(false);
    BSCCamaguey.setSelected(false);
    BSCHolguin.setSelected(false);
    BSCCubanacan.setSelected(false);
    DestinoFJ.setEnabled(true);
    BoardType.setEnabled(false);
    DestinoFJ.removeAllItems();
    FJtext.setEnabled(true);
    FechaText.setEnabled(true);
    OTText.setEnabled(true);
    Asunto.setEnabled(true);
    Recorrido.setEnabled(true);
    Dip.setText(" ");
    Dip.setEnabled(false);
    BSCVClara.setSelected(true);
    Device.setEnabled(true);
    Dip.setEnabled(true);
    Asunto.setText(" ");
    Recorrido.setText(" ");
    Fj.setSelected(false);
    OT.setSelected(false);
    Fecha.setSelected(false);
    ContBusqueda.setEnabled(false);
   String list[]={"","RB2"};
    JComboBox cb=new JComboBox(list);
    Device.setModel(cb.getModel());
    tip=2;
    org="tb_bsc_vclara";//dice el nodo a buscar
    org1="tb_cell_vclara";
    nombre_nodo="BSC VCLARA";
    FJtext.setText(" ");
    FechaText.setText(" ");
    OTText.setText(" ");
    ContBusqueda.setText(" ");
    aa=0;//para que no se levante el DeviceFJ
    veces=0;
    Elija.setSelected(false);
    Elija1.setSelected(false);
    Celdas.setText(" ");
    DestinoBSC.setText(" ");
    TG.setEnabled(false);
    TG.setText(" ");
    elija=5;
    try{
            Class.forName("com.mysql.jdbc.Driver"); // 2005 version
            con = DriverManager.getConnection("jdbc:mysql://10.94.1.143:3306/gestion_trafico","etecsa","etecsa");
            java.sql.Statement  st = con.createStatement();
            String strSQL="Select rsite from "+org+"  ";
            rs =st.executeQuery(strSQL); 
                
           DestinoFJ.setEnabled(true);
                 while (rs.next()) 
                 {
                    
                         DestinoFJ.addItem(rs.getObject("rsite") );      
                                 
                      

                 }
                  
                   //Muestra la ruta independientemente del tipo de nodo
                   valor=" ";
                   valor1=" ";


                   rs.close();           
                   st.close(); 
                   con.close();

                       
}
    
catch ( SQLException excepcionSql)
{ 
JOptionPane.showMessageDialog( null, excepcionSql.getMessage(),"Error en base de datos", JOptionPane.ERROR_MESSAGE );
}

//errores con la carga del controlador de la base de datos(Driver)

catch ( ClassNotFoundException claseNoEncontrada ){
JOptionPane.showMessageDialog( null, claseNoEncontrada.getMessage(),"No se encontró el controlador", JOptionPane.ERROR_MESSAGE );
} 
}//GEN-LAST:event_BSCVClaraActionPerformed

private void BSCCamagueyActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_BSCCamagueyActionPerformed
// TODO add your handling code here:
    y=0;//Para saber que esta desactivado los MSoft
    MsoftHabana.setSelected(false);
    MsoftJaguey.setSelected(false);
    MsoftCamaguey.setSelected(false);
    MSCCubanacan.setSelected(false);
    BSCPanorama.setSelected(false);
    BSCZTE.setSelected(false);
    BSCJaguey.setSelected(false);
    BSCVClara.setSelected(false);
    //BSCCamaguey.setSelected(false);
    BSCHolguin.setSelected(false);
    BSCCubanacan.setSelected(false);
    BoardType.setEnabled(false);
     DestinoFJ.setEnabled(false);
    DestinoFJ.removeAllItems();
    FJtext.setEnabled(true);
    FechaText.setEnabled(true);
    OTText.setEnabled(true);
    Asunto.setEnabled(true);
    Recorrido.setEnabled(true);
    Dip.setText(" ");
    Dip.setEnabled(false);
    BSCCamaguey.setSelected(true);
    Device.setEnabled(true);
    Dip.setEnabled(true);
    Asunto.setText(" ");
    Recorrido.setText(" ");
    Fj.setSelected(false);
    OT.setSelected(false);
    Fecha.setSelected(false);
    ContBusqueda.setEnabled(false);
    FJtext.setText(" ");
    FechaText.setText(" ");
    OTText.setText(" ");
    ContBusqueda.setText(" ");
    aa=0;//para que no se levante el DeviceFJ
   //String list[]={"","RBL2"};
    //JComboBox cb=new JComboBox(list);
    //Device.setModel(cb.getModel());
    tip=2;
    org="tb_cell_cam";//dice el nodo a buscar
    org1="null";
    nombre_nodo="BSC CAMAGÜEY";
    Cantidad.setText(" "); Cantidad.setText(" ");//Pone vacio la cantidad de ocurrencia
    veces=0;
    Elija.setSelected(false);
    Elija1.setSelected(false);
    elija=5;
    Celdas.setText(" ");
    DestinoBSC.setText(" ");
    TG.setEnabled(false);
    TG.setText(" ");
    
    
    
    try{
            Class.forName("com.mysql.jdbc.Driver"); // 2005 version
            con = DriverManager.getConnection("jdbc:mysql://10.94.1.143:3306/gestion_trafico","etecsa","etecsa");
            java.sql.Statement  st = con.createStatement();
            String strSQL="Select distinct rsite from "+org+" where id_bsc=10  group by rsite";
            rs =st.executeQuery(strSQL); 
                
           DestinoFJ.setEnabled(true);
                 while (rs.next()) 
                 {
                    
                         DestinoFJ.addItem(rs.getObject("rsite") );      
                                 
                      

                 }
                  
                   //Muestra la ruta independientemente del tipo de nodo
                   valor=" ";
                   valor1=" ";


                   rs.close();           
                   st.close(); 
                   con.close();

                       
}
    
catch ( SQLException excepcionSql)
{ 
JOptionPane.showMessageDialog( null, excepcionSql.getMessage(),"Error en base de datos", JOptionPane.ERROR_MESSAGE );
}

//errores con la carga del controlador de la base de datos(Driver)

catch ( ClassNotFoundException claseNoEncontrada ){
JOptionPane.showMessageDialog( null, claseNoEncontrada.getMessage(),"No se encontró el controlador", JOptionPane.ERROR_MESSAGE );
} 
}//GEN-LAST:event_BSCCamagueyActionPerformed

private void Buscar2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_Buscar2ActionPerformed
// TODO add your handling code here:
    String cel=Celdas.getText();
    cel=cel.replaceAll(" ", "");
    String tg=TG.getText();
    tg=tg.replaceAll(" ", "");
    dev1=Dip.getText().toString();//obtengo el valor del dip
    dev1=dev1.replaceAll(" ","");
    if(tip==1 || tip==2)
    {
        if(elija>1)//saber que elija no esta activo
        {
    dev2=Device.getSelectedItem().toString();//obtengo tipo de device
        }
    }
    //index=jComboBox1.getSelectedItem().toString();
    try{
            Class.forName("com.mysql.jdbc.Driver"); // 2005 version
            con = DriverManager.getConnection("jdbc:mysql://10.94.1.143:3306/gestion_trafico","etecsa","etecsa");
            java.sql.Statement  st = con.createStatement();
            
            
            switch(elija)
            {
                case 0:
                    String strSQL="Select t2.rsite from "+org1+" t1, "+org+" t2 where t1.tg=t2.tg and cell='"+cel+"' ";//Para poner el nombre del sitio segun la celda
                    rs =st.executeQuery(strSQL);
                    break;
                case 1:
                    if(!(BSCCamaguey.isSelected()||BSCHolguin.isSelected()||BSCJaguey.isSelected()||BSCZTE.isSelected()))
                    {
                    String strSQL1="Select rsite from "+org+" where tg='"+tg+"' ";//Para poner el nombre del sitio segun la celda
                    rs =st.executeQuery(strSQL1);
                    
                    }
                   break;
                        
            }
            
            
            
            if(!(Elija.isSelected()||Elija1.isSelected()))//Saber si esta activo el checkbox
            {
            
                    switch(tip)
                    {
                        case 2:    //Para los BSC            
                                String strSQL="Select rsite from "+org+" where dip='"+dev1.concat(dev2)+"' ";
                                rs =st.executeQuery(strSQL); 
                                break;

                        case 1: //Para el MSC
                                String strSQL1="Select rutas from "+org+" where dip='"+dev1+"' and device='"+dev2+"'";
                                rs =st.executeQuery(strSQL1); 
                                break;


                    }  
            }
                 while (rs.next()) 
                 {
                   
                   valor1=rs.getString(1);//tengo las rutas del msc

                                    
                 }
          
                   
                   DestinoBSC.setEnabled(true);
                   DestinoBSC.setText(valor1); //Muestra la ruta independientemente del tipo de nodo
                   valor=" ";
                   valor1=" ";


                   rs.close();           
                   st.close(); 
                   con.close();

                       
}
    
catch ( SQLException excepcionSql)
{ 
JOptionPane.showMessageDialog( null, excepcionSql.getMessage(),"Error en base de datos", JOptionPane.ERROR_MESSAGE );
}

//errores con la carga del controlador de la base de datos(Driver)

catch ( ClassNotFoundException claseNoEncontrada ){
JOptionPane.showMessageDialog( null, claseNoEncontrada.getMessage(),"No se encontró el controlador", JOptionPane.ERROR_MESSAGE );
} 
}//GEN-LAST:event_Buscar2ActionPerformed

private void Buscar3ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_Buscar3ActionPerformed
// TODO add your handling code here:
       
    Fj.setEnabled(true);
    OT.setEnabled(true);
   Similidad sm=new Similidad(nombre_nodo,(String)DestinoFJ.getSelectedItem());
   String j=null;
    j=sm.d;
   String get=ContBusqueda.getText();
   get=get.replaceAll(" ", "");
    
    try{
Class.forName("com.mysql.jdbc.Driver"); // 2005 version
  con = DriverManager.getConnection("jdbc:mysql://10.94.1.143:3306/gestion_trafico","etecsa","etecsa");

           java.sql.Statement  st = con.createStatement();
           
         switch(aa)
         {
                 case 0:
                     String strSQL="Select count(hasta) as nm from tb_recorrido where hasta='"+j+"' and desde='"+nombre_nodo+"'  group by hasta";
                      rs =  st.executeQuery(strSQL);//Este es para la busqueda por sitios
                      
                     break;
                 case 1:
                     String strSQL1="Select count(flujo) as nm1 from tb_recorrido where flujo='"+get+"' and desde='"+nombre_nodo+"'  group by flujo,fecha";
                      rs =  st.executeQuery(strSQL1);//Busqueda por FJ
                     break;
                 case 2:
                 String strSQL2="Select count(fecha) as nm2 from tb_recorrido where fecha='"+get+"' and desde='"+nombre_nodo+"'  group by fecha";
                      rs =  st.executeQuery(strSQL2);//Busqueda por fecha       
                     break;
                 case 3:
                 String strSQL3="Select count(orden) as nm3 from tb_recorrido where orden='"+get+"' and desde='"+nombre_nodo+"'  group by orden,fecha";
                      rs =  st.executeQuery(strSQL3);//Busqueda por OT
                     break;
         }  
       
             String r=null;
      int i=0;
 while (rs.next()) 
 {
          switch(aa)
          {
              case 0:
                   cont=rs.getString("nm");//tengo la cantidad de eventos iguales
                   break;
              case 1:
                   cont=rs.getString("nm1");//tengo la cantidad de eventos iguales
                   break;
              case 2:
                   cont=rs.getString("nm2");//tengo la cantidad de eventos iguales
                   break;
              case 3:
                   cont=rs.getString("nm3");//tengo la cantidad de eventos iguales
                   break;
               
          }    
          
          //Cantidad.setText(cont);  
        /*Recorrido.setText(rs.getString("recorrido"));
          Asunto.setText(rs.getString("asunto"));
          FJtext.setText(rs.getString("flujo"));
          OTText.setText(rs.getString("orden"));
          FechaText.setText(rs.getString("fecha"));*/
          
                 
 }
       switch(aa)
         {
                 case 0:
                      String strSQL_0="Select orden,asunto,flujo,recorrido,fecha from tb_recorrido where hasta='"+j+"' and desde='"+nombre_nodo+"'  group by fecha";
                      rs1 =  st.executeQuery(strSQL_0);
                      
                     break;
                 case 1:
                     String strSQL_1="Select distinct orden,asunto,flujo,recorrido,fecha from tb_recorrido where flujo='"+get+"' and desde='"+nombre_nodo+"'  group by flujo,fecha";
                      rs1 =  st.executeQuery(strSQL_1);//Busqueda por FJ
                     break;
                 case 2:
                 String strSQL_2="Select distinct orden,asunto,flujo,recorrido,fecha from tb_recorrido where fecha='"+get+"' and desde='"+nombre_nodo+"'  group by fecha";
                      rs1 =  st.executeQuery(strSQL_2);//Busqueda por fecha       
                     break;
                 case 3:
                 String strSQL_4="Select distinct orden,asunto,flujo,recorrido,fecha from tb_recorrido where orden='"+get+"' and desde='"+nombre_nodo+"'  group by orden,fecha";
                      rs1 =  st.executeQuery(strSQL_4);//Busqueda por OT
                     break;
         }  
      
      
     
      
                      
        while(rs1.next())
        {
             cont_fecha[i]=rs1.getString("fecha");
               cont_recor[i]=rs1.getString("recorrido");
               cont_asunt0[i]=rs1.getString("asunto");
               cont_ot[i]=rs1.getString("orden");
               cont_flujo[i]=rs1.getString("flujo");
              i++;     
        
        
        }
                      
            if(veces<Integer.parseInt(cont))  
              {
                 
              Cantidad.setText(cont);  
              Recorrido.setText(cont_recor[veces]);
              Asunto.setText(cont_asunt0[veces]);
              FJtext.setText(cont_flujo[veces]);
              OTText.setText(cont_ot[veces]);
              FechaText.setText(cont_fecha[veces]);
              veces++;
              
              }
                     
              else
              {
              
                Cantidad.setText("");
                Recorrido.setText("");
          Asunto.setText("");
          FJtext.setText("");
          OTText.setText("");
          FechaText.setText("");
           veces=0;
             
              }
      
    
         
     
          
       
           //jTextField3.setText(r); 
             //
   rs.close();           
   st.close(); 
   con.close();
       
                
}
    
catch ( SQLException excepcionSql)
{ 
JOptionPane.showMessageDialog( null, excepcionSql.getMessage(),"Error en base de datos", JOptionPane.ERROR_MESSAGE );
}

//errores con la carga del controlador de la base de datos(Driver)

catch ( ClassNotFoundException claseNoEncontrada ){
JOptionPane.showMessageDialog( null, claseNoEncontrada.getMessage(),"No se encontró el controlador", JOptionPane.ERROR_MESSAGE );
} 
   
   
    
}//GEN-LAST:event_Buscar3ActionPerformed

private void FjActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_FjActionPerformed
// TODO add your handling code here:
    ContBusqueda.setEnabled(true);
    DestinoFJ.setEnabled(false);
    Fecha.setSelected(false);
    OT.setSelected(false);
    Asunto.setText(" ");
    DestinoFJ.setSelectedIndex(0);
    Recorrido.setText(" ");
    FJtext.setText(" ");
    FechaText.setText(" ");
    OTText.setText(" ");
    ContBusqueda.setText(" ");
    Cantidad.setText(" ");
    aa=1;
    veces=0;
}//GEN-LAST:event_FjActionPerformed

private void FechaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_FechaActionPerformed
// TODO add your handling code here:
    ContBusqueda.setEnabled(true);
    DestinoFJ.setEnabled(false);
    OT.setSelected(false);
    Fj.setSelected(false);
    Asunto.setText(" ");
    Recorrido.setText(" ");
    FJtext.setText(" ");
    FechaText.setText(" ");
    OTText.setText(" ");
    ContBusqueda.setText(" ");
    aa=2;
   DestinoFJ.setSelectedIndex(0);
   Cantidad.setText(" ");
   veces=0;
}//GEN-LAST:event_FechaActionPerformed

private void OTActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_OTActionPerformed
// TODO add your handling code here:
    ContBusqueda.setEnabled(true);
    DestinoFJ.setEnabled(false);
     Fj.setSelected(false);
     Fecha.setSelected(false);
     Asunto.setText(" ");
    Recorrido.setText(" ");
    FJtext.setText(" ");
    FechaText.setText(" ");
    OTText.setText(" ");
    ContBusqueda.setText(" ");
    aa=3;
   DestinoFJ.setSelectedIndex(0);
   Cantidad.setText(" ");
            veces=0;
}//GEN-LAST:event_OTActionPerformed

private void ElijaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_ElijaActionPerformed
// TODO add your handling code here:
   elija=0;
   
    if(Elija.isSelected())
    {
    Celdas.setEnabled(true);
    Celdas.setText(" ");
    Dip.setEnabled(false);
    Dip.setText(" ");
    Device.setEnabled(false);
    Device.removeAllItems();
    DestinoBSC.setText(" ");
    Elija1.setSelected(false);
    TG.setText(" ");
    TG.setEnabled(false);
    }
    else
    {
       Celdas.setEnabled(false);
    Celdas.setText(" ");
    Dip.setEnabled(true);
    Device.setEnabled(true); 
     Device.setSelectedIndex(0);
    DestinoBSC.setText(" ");
    Dip.setText(" ");
    }
   
    
}//GEN-LAST:event_ElijaActionPerformed

private void DestinoFJActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_DestinoFJActionPerformed
// TODO add your handling code here:
}//GEN-LAST:event_DestinoFJActionPerformed

private void Elija1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_Elija1ActionPerformed
// TODO add your handling code here:
  
     elija=1;
    if(Elija1.isSelected())
    {
        TG.setEnabled(true);
        TG.setText(" ");
        Dip.setEnabled(false);
        Dip.setText(" ");
        DestinoBSC.setText(" ");
        Celdas.setEnabled(false);
        Celdas.setText(" ");
        Elija.setSelected(false);
        Device.removeAllItems();
        Device.setEnabled(false);
    }
    else
    {
        TG.setEnabled(false);
        TG.setText(" ");
        Dip.setEnabled(true);
        DestinoBSC.setText(" ");
        Dip.setText(" ");
    }
}//GEN-LAST:event_Elija1ActionPerformed

private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed
// TODO add your handling code here:
    String ent=Entrar.getText();
    
       
        if(y<4)
        {
        Localizador loc=new Localizador(ent,y);
        String bsc=loc.bsc;
        traductor_bsc trad=new traductor_bsc(bsc);
        tabla=trad.tb_bsc;
       tabla1=trad.tb_cell;
       cell=loc.cell;
       cell=cell.replaceAll("_", "");
        }
        else
        {
         Localizador loc=new Localizador(ent,y);
                  
         tabla=loc.tb_bsc;
         tabla1=loc.tb_cell;
        //String bsc=loc.bsc;
         cell=loc.cellda;
        //cell=cell.replaceAll("_", "");
        
        
        }
    
    
    
      try{
Class.forName("com.mysql.jdbc.Driver"); // 2005 version
 Connection con = DriverManager.getConnection("jdbc:mysql://10.94.1.143:3306/gestion_trafico","etecsa","etecsa");
Statement st = (Statement) con.createStatement();

if(y==2 ||y==3)
{
String strSQL="Select distinct rsite from "+tabla1+" where cell='"+cell+"'  group by rsite ";
            rs = st.executeQuery(strSQL);

}
else
{
String strSQL="Select distinct t2.rsite from "+tabla+" t2, "+tabla1+" t1 where t2.tg=t1.tg and cell='"+cell+"'  group by rsite ";
            rs = st.executeQuery(strSQL); 
}

while(rs.next())
{

Mostrar.setText(rs.getString(1));



}
            
            
            
            
st.close();
con.close();//se cierra la conexion con la base de datos
 
}//excepcionSql = puede ponerle otro nombre
catch ( SQLException excepcionSql)
{ 
JOptionPane.showMessageDialog( null, excepcionSql.getMessage(),"Error en base de datos", JOptionPane.ERROR_MESSAGE );
}

//errores con la carga del controlador de la base de datos(Driver)

catch ( ClassNotFoundException claseNoEncontrada ){
JOptionPane.showMessageDialog( null, claseNoEncontrada.getMessage(),"No se encontró el controlador", JOptionPane.ERROR_MESSAGE );
}
                  
          
        
    
    
    
}//GEN-LAST:event_jButton1ActionPerformed

private void EntrarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_EntrarActionPerformed
// TODO add your handling code here:
}//GEN-LAST:event_EntrarActionPerformed

    private void DeviceActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_DeviceActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_DeviceActionPerformed

    

    
    /**
    * @param args the command line arguments
    */
    public static void main(String args[]) {
        JFrame.setDefaultLookAndFeelDecorated(true);
        //SubstanceLookAndFeel.setSkin("org.jvnet.substance.skin.BusinessBlackSteelSkin");
        //SubstanceLookAndFeel.setCurrentTheme("org.jvnet.substance.these.SubstanceBrownThese");
         //SubstanceLookAndFeel.setCurrentWatermark("org.jvnet.substance.watermark.SubstanceLatchWatermark");
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new Buscador().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JTextArea Asunto;
    private javax.swing.JRadioButton BSCCamaguey;
    private javax.swing.JRadioButton BSCCubanacan;
    private javax.swing.JRadioButton BSCHolguin;
    private javax.swing.JRadioButton BSCJaguey;
    private javax.swing.JRadioButton BSCPanorama;
    private javax.swing.JRadioButton BSCVClara;
    private javax.swing.JRadioButton BSCZTE;
    private javax.swing.JComboBox BoardType;
    private javax.swing.JButton Buscar1;
    private javax.swing.JButton Buscar2;
    private javax.swing.JButton Buscar3;
    private javax.swing.JTextField Cantidad;
    private javax.swing.JTextField Celdas;
    private javax.swing.JTextField ContBusqueda;
    private javax.swing.JTextField DestinoBSC;
    private javax.swing.JComboBox DestinoFJ;
    private javax.swing.JTextField DestinoMsot;
    private javax.swing.JComboBox Device;
    private javax.swing.JTextField Dip;
    private javax.swing.JCheckBox Elija;
    private javax.swing.JCheckBox Elija1;
    private javax.swing.JTextField Entrar;
    private javax.swing.JTextField FJtext;
    private javax.swing.JRadioButton Fecha;
    private javax.swing.JTextField FechaText;
    private javax.swing.JRadioButton Fj;
    private javax.swing.JRadioButton MSCCubanacan;
    private javax.swing.JTextField Mostrar;
    private javax.swing.JRadioButton MsoftCamaguey;
    private javax.swing.JRadioButton MsoftHabana;
    private javax.swing.JRadioButton MsoftJaguey;
    private javax.swing.JRadioButton OT;
    private javax.swing.JTextField OTText;
    private javax.swing.JTextArea Recorrido;
    private javax.swing.JTextField TG;
    private javax.swing.JTextField TID;
    private javax.swing.ButtonGroup buttonGroup1;
    private javax.swing.JButton jButton1;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel10;
    private javax.swing.JLabel jLabel11;
    private javax.swing.JLabel jLabel12;
    private javax.swing.JLabel jLabel13;
    private javax.swing.JLabel jLabel14;
    private javax.swing.JLabel jLabel15;
    private javax.swing.JLabel jLabel16;
    private javax.swing.JLabel jLabel17;
    private javax.swing.JLabel jLabel18;
    private javax.swing.JLabel jLabel19;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel20;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel10;
    private javax.swing.JPanel jPanel11;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JPanel jPanel3;
    private javax.swing.JPanel jPanel4;
    private javax.swing.JPanel jPanel5;
    private javax.swing.JPanel jPanel6;
    private javax.swing.JPanel jPanel7;
    private javax.swing.JPanel jPanel8;
    private javax.swing.JPanel jPanel9;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JScrollPane jScrollPane2;
    private javax.swing.JSpinner jSpinner1;
    private javax.swing.JSpinner jSpinner2;
    private javax.swing.JSpinner jSpinner3;
    private javax.swing.JSpinner jSpinner4;
    // End of variables declaration//GEN-END:variables

}
