package mapa_cubacel;


import java.awt.Graphics;
import java.awt.Image;

/*
 * FondoOpciones.java
 *
 * Created on September 11, 2011, 3:03 AM
 */
import java.awt.Toolkit;



/**
 *
 * @author  heidy.capote
 */
public class FondoOpciones extends javax.swing.JPanel {
public Image img1;
    /** Creates new form FondoOpciones */
    public FondoOpciones() {
        initComponents();
        img1=Toolkit.getDefaultToolkit().getImage("Img/Habana.jpg");
        this.setSize(400, 400);
    }

    public void paintComponent(Graphics g)
    { 
                   
    super.paintComponent(g);
    if(img1 !=null)
    {
       
     g.drawImage(img1, 0, 0, this);   
    
    
    }
 }
    /** This method is called from within the constructor to
     * initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is
     * always regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 400, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 300, Short.MAX_VALUE)
        );
    }// </editor-fold>//GEN-END:initComponents


    // Variables declaration - do not modify//GEN-BEGIN:variables
    // End of variables declaration//GEN-END:variables

}
