/*
 * To change this template, choose Tools | Templates
 * and open the template in the editor.
 */

package mapa_cubacel;

import java.awt.BorderLayout;
import java.awt.Dimension;
import java.sql.Connection;

/*
 * Link_Mapa.java
 *
 * Created on December 25, 2011, 8:40 PM
 */
import java.sql.DriverManager;
import java.sql.ResultSet;
import java.sql.SQLException;
import javax.swing.JInternalFrame;
import javax.swing.JOptionPane;
import javax.swing.JScrollPane;
import javax.swing.JTable;
import javax.swing.table.DefaultTableModel;



/**
 *
 * @author  heidy.capote
 */
public class Link_Mapa extends javax.swing.JFrame {
private JInternalFrame jInternalFrame1;
String valor;
    /** Creates new form Link_Mapa */
    public Link_Mapa(int w) {
        switch(w)
        {
            case 0:
                valor="tb_link_msfhab";
                
                break;
            case 1:
                valor="tb_link_msfjaguey";
                break;
            case 2:
                valor="tb_link_msc";
                break;
            case 3:
                valor="tb_link_msfcam";
                break;
        }
                
                
                
                
        initComponents();
        this.setSize(1100,720);
        Tabla();
    }

    private Link_Mapa() {
        throw new UnsupportedOperationException("Not yet implemented");
    }

   
public void Tabla()
{
try{
Class.forName("com.mysql.jdbc.Driver"); // 2005 version
Connection con = DriverManager.getConnection("jdbc:mysql://10.94.1.143/mysql","root","etecsa");

            java.sql.Statement st =con.createStatement();
//st.executeUpdate("CREATE TABLE contacto (id INT AUTO_INCREMENT, PRIMARY KEY(id), nombre VARCHAR(20), apellidos VARCHAR(20), telefono VARCHAR(20))");
String strSQL="Select LinkSet,SPID,SLC from "+valor+" ";
ResultSet rs = st.executeQuery(strSQL); 

DefaultTableModel modelo = new DefaultTableModel();
JTable tabla = new JTable(modelo);
JScrollPane scrollpane = new JScrollPane(tabla);

tabla.setPreferredScrollableViewportSize(new Dimension(500, 220));
//this.pack();

// Creamos las columnas.
modelo.addColumn("LinkSet");
modelo.addColumn("SPID");
modelo.addColumn("SLC");



            jInternalFrame1 = new javax.swing.JInternalFrame();
            jInternalFrame1.setTitle("Informacion de rutas y links");
             //jInternalFrame1.add(dial);
            jInternalFrame1.setResizable(false);
            //jInternalFrame1.setClosable(true);
            jInternalFrame1.setVisible(true);
            getContentPane().add(jInternalFrame1);
            jInternalFrame1.setBounds(50, 300, 1000, 360);
            jInternalFrame1.getContentPane().add(scrollpane, BorderLayout.CENTER);
       


while (rs.next()) {
   
  //System.out.println(rs.getString(1));
  //System.out.println(rs.getFloat(2));
  //System.out.println(rs.getInt(3));
       
    Object [] fila = new Object[3]; 
    for (int i=0;i<3;i++)
      fila[i] = rs.getObject(i+1); // El primer indice en rs es el 1, no el cero, por eso se suma 1.

   // Se añade al modelo la fila completa.
   modelo.addRow(fila); 
  
  }  // close all the connections.

  rs.close();
  st.close();




con.close();//se cierra la conexion con la base de datos
 
}//excepcionSql = puede ponerle otro nombre
catch ( SQLException excepcionSql)
{ 
JOptionPane.showMessageDialog( null, excepcionSql.getMessage(),"Error en base de datos", JOptionPane.ERROR_MESSAGE );
}

//errores con la carga del controlador de la base de datos(Driver)

catch ( ClassNotFoundException claseNoEncontrada ){
JOptionPane.showMessageDialog( null, claseNoEncontrada.getMessage(),"No se encontró el controlador", JOptionPane.ERROR_MESSAGE );
}



}
        
    /** This method is called from within the constructor to
     * initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is
     * always regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">                          
    private void initComponents() {

        /*jLabel1 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);
        getContentPane().setLayout(null);

        jLabel1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Img/Hlr.JPG"))); // NOI18N
        getContentPane().add(jLabel1);
        jLabel1.setBounds(90, -60, 910, 410);*/

        pack();
    }// </editor-fold>                        

    /**
    * @param args the command line arguments
    */
    public static void main(String args[]) {
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new Link_Mapa().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify                     
    private javax.swing.JLabel jLabel1;
    // End of variables declaration                   

}
