package mapa_cubacel;


import java.awt.BorderLayout;
import java.awt.Color;
import java.awt.Dimension;
import java.sql.Connection;
import java.sql.DriverManager;
import java.sql.ResultSet;
import java.sql.SQLException;
import javax.swing.JInternalFrame;
import javax.swing.JLabel;

/*
 * MapaOComerciales.java
 *
 * Created on September 14, 2011, 8:42 PM
 */
import javax.swing.JOptionPane;
import javax.swing.JScrollPane;
import javax.swing.JTable;
import javax.swing.table.DefaultTableModel;



/**
 *
 * @author  heidy.capote
 */
public class MapaOComerciales extends javax.swing.JFrame {
private JLabel jLabel2;
private JInternalFrame jInternalFrame1;
    /** Creates new form MapaOComerciales */
    public MapaOComerciales() {
        initComponents();
        this.setSize(1100,700);
    }


    /** This method is called from within the constructor to
     * initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is
     * always regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        btn1 = new javax.swing.JButton();
        btn2 = new javax.swing.JButton();
        btn3 = new javax.swing.JButton();
        btn4 = new javax.swing.JButton();
        btn5 = new javax.swing.JButton();
        btn6 = new javax.swing.JButton();
        jLabel1 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);
        getContentPane().setLayout(null);

        btn1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Imagenes/BSC.JPG"))); // NOI18N
        btn1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btn1ActionPerformed(evt);
            }
        });
        getContentPane().add(btn1);
        btn1.setBounds(620, 170, 30, 20);

        btn2.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Imagenes/BSC.JPG"))); // NOI18N
        btn2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btn2ActionPerformed(evt);
            }
        });
        getContentPane().add(btn2);
        btn2.setBounds(610, 263, 30, 20);

        btn3.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Imagenes/BSC.JPG"))); // NOI18N
        btn3.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btn3ActionPerformed(evt);
            }
        });
        getContentPane().add(btn3);
        btn3.setBounds(540, 390, 30, 20);

        btn4.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Imagenes/BSC.JPG"))); // NOI18N
        btn4.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btn4ActionPerformed(evt);
            }
        });
        getContentPane().add(btn4);
        btn4.setBounds(430, 380, 30, 20);

        btn5.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Imagenes/BSC.JPG"))); // NOI18N
        btn5.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btn5ActionPerformed(evt);
            }
        });
        getContentPane().add(btn5);
        btn5.setBounds(320, 390, 30, 20);

        btn6.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Imagenes/BSC.JPG"))); // NOI18N
        btn6.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btn6ActionPerformed(evt);
            }
        });
        getContentPane().add(btn6);
        btn6.setBounds(300, 250, 30, 20);

        jLabel1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Imagenes/Habana.JPG"))); // NOI18N
        getContentPane().add(jLabel1);
        jLabel1.setBounds(50, 40, 960, 610);

        pack();
    }// </editor-fold>//GEN-END:initComponents

private void btn1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn1ActionPerformed
// TODO add your handling code here:
    try{
Class.forName("com.microsoft.sqlserver.jdbc.SQLServerDriver"); // 2005 version
Connection con = DriverManager.getConnection("jdbc:sqlserver://10.50.103.70:1433;databaseName=gestion_trafico;user=etecsa;password=etecsa;");

            java.sql.Statement st =con.createStatement();
//st.executeUpdate("CREATE TABLE contacto (id INT AUTO_INCREMENT, PRIMARY KEY(id), nombre VARCHAR(20), apellidos VARCHAR(20), telefono VARCHAR(20))");
String strSQL="Select rutas,cic from TB_Rutas ";
ResultSet rs = st.executeQuery(strSQL); 

DefaultTableModel modelo = new DefaultTableModel();
JTable tabla = new JTable(modelo);
tabla.setForeground(Color.black); 
JScrollPane scrollpane = new JScrollPane(tabla);

tabla.setPreferredScrollableViewportSize(new Dimension(500, 220));
//this.pack();

// Creamos las columnas.
modelo.addColumn("rutas");
modelo.addColumn("cic");
//modelo.addColumn("SLC");


jLabel1.setVisible(false);
            btn1.setVisible(false);
            btn2.setVisible(false);
            btn3.setVisible(false);
            btn6.setVisible(false);
            btn4.setVisible(false);
            btn5.setVisible(false);
            //btn7.setVisible(false);
            jLabel2 = new javax.swing.JLabel();

            jLabel2.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Imagenes/MinilinkTop.JPG"))); // NOI18N
            getContentPane().add(jLabel2);
           // getContentPane().add(tabla);
            jLabel2.setBounds(60, 0, 1030, 300);
            jInternalFrame1 = new javax.swing.JInternalFrame();
            jInternalFrame1.setTitle("Informaciones adicionales");
             //jInternalFrame1.add(dial);
            jInternalFrame1.setResizable(false);
            jInternalFrame1.setClosable(true);
            jInternalFrame1.setVisible(true);
            getContentPane().add(jInternalFrame1);
            jInternalFrame1.setBounds(50, 280, 1000, 385);
            jInternalFrame1.getContentPane().add(scrollpane, BorderLayout.CENTER);
            jInternalFrame1.addInternalFrameListener(new javax.swing.event.InternalFrameListener() {
            
                public void internalFrameActivated(javax.swing.event.InternalFrameEvent evt) {
                }

                public void internalFrameClosed(javax.swing.event.InternalFrameEvent evt) {
                    jInternalFrame1InternalFrameClosed(evt);
                }

                public void internalFrameClosing(javax.swing.event.InternalFrameEvent evt) {
                }

                public void internalFrameDeactivated(javax.swing.event.InternalFrameEvent evt) {
                }

                public void internalFrameDeiconified(javax.swing.event.InternalFrameEvent evt) {
                }

                public void internalFrameIconified(javax.swing.event.InternalFrameEvent evt) {
                }

                public void internalFrameOpened(javax.swing.event.InternalFrameEvent evt) {
                }
            });


while (rs.next()) {
   
  //System.out.println(rs.getString(1));
  //System.out.println(rs.getFloat(2));
  //System.out.println(rs.getInt(3));
       
    Object [] fila = new Object[2]; 
    for (int i=0;i<2;i++)
      fila[i] = rs.getObject(i+1); // El primer indice en rs es el 1, no el cero, por eso se suma 1.

   // Se añade al modelo la fila completa.
   modelo.addRow(fila); 
  
  }  // close all the connections.

  rs.close();
  st.close();




con.close();//se cierra la conexion con la base de datos
 
}//excepcionSql = puede ponerle otro nombre
catch ( SQLException excepcionSql)
{ 
JOptionPane.showMessageDialog( null, excepcionSql.getMessage(),"Error en base de datos", JOptionPane.ERROR_MESSAGE );
}

//errores con la carga del controlador de la base de datos(Driver)

catch ( ClassNotFoundException claseNoEncontrada ){
JOptionPane.showMessageDialog( null, claseNoEncontrada.getMessage(),"No se encontró el controlador", JOptionPane.ERROR_MESSAGE );
}

}//GEN-LAST:event_btn1ActionPerformed

private void btn2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn2ActionPerformed
// TODO add your handling code here:
     jLabel1.setVisible(false);
    btn1.setVisible(false);
    
    
    btn2.setVisible(false);
    btn3.setVisible(false);
    btn6.setVisible(false);
   
    btn4.setVisible(false);
    btn5.setVisible(false);
    
    jLabel2 = new javax.swing.JLabel();

    jLabel2.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Imagenes/MinilinkTop.JPG"))); // NOI18N

    getContentPane().add(jLabel2);
    jLabel2.setBounds(60, 0, 1030, 300);
    jInternalFrame1 = new javax.swing.JInternalFrame();
    jInternalFrame1.setTitle("Informaciones adicionales");
  
    jInternalFrame1.setResizable(false);
    jInternalFrame1.setClosable(true);
    jInternalFrame1.setVisible(true);
    getContentPane().add(jInternalFrame1);
    jInternalFrame1.setBounds(50, 280, 1000, 400);
    
   jInternalFrame1.addInternalFrameListener(new javax.swing.event.InternalFrameListener() {
    public void internalFrameActivated(javax.swing.event.InternalFrameEvent evt) {
    }
    public void internalFrameClosed(javax.swing.event.InternalFrameEvent evt) {
        jInternalFrame1InternalFrameClosed(evt);
    }
    public void internalFrameClosing(javax.swing.event.InternalFrameEvent evt) {
    }
    public void internalFrameDeactivated(javax.swing.event.InternalFrameEvent evt) {
    }
    public void internalFrameDeiconified(javax.swing.event.InternalFrameEvent evt) {
    }
    public void internalFrameIconified(javax.swing.event.InternalFrameEvent evt) {
    }
    public void internalFrameOpened(javax.swing.event.InternalFrameEvent evt) {
    }
});
}//GEN-LAST:event_btn2ActionPerformed

private void btn3ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn3ActionPerformed
// TODO add your handling code here:
     jLabel1.setVisible(false);
    btn1.setVisible(false);
    
    
    btn2.setVisible(false);
    btn3.setVisible(false);
    btn6.setVisible(false);
   
    btn4.setVisible(false);
    btn5.setVisible(false);
    
    jLabel2 = new javax.swing.JLabel();

    jLabel2.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Imagenes/MinilinkTop.JPG"))); // NOI18N

    getContentPane().add(jLabel2);
    jLabel2.setBounds(60, 0, 1030, 300);
    jInternalFrame1 = new javax.swing.JInternalFrame();
    jInternalFrame1.setTitle("Informaciones adicionales");
  
    jInternalFrame1.setResizable(false);
    jInternalFrame1.setClosable(true);
    jInternalFrame1.setVisible(true);
    getContentPane().add(jInternalFrame1);
    jInternalFrame1.setBounds(50, 280, 1000, 400);
    
   jInternalFrame1.addInternalFrameListener(new javax.swing.event.InternalFrameListener() {
    public void internalFrameActivated(javax.swing.event.InternalFrameEvent evt) {
    }
    public void internalFrameClosed(javax.swing.event.InternalFrameEvent evt) {
        jInternalFrame1InternalFrameClosed(evt);
    }
    public void internalFrameClosing(javax.swing.event.InternalFrameEvent evt) {
    }
    public void internalFrameDeactivated(javax.swing.event.InternalFrameEvent evt) {
    }
    public void internalFrameDeiconified(javax.swing.event.InternalFrameEvent evt) {
    }
    public void internalFrameIconified(javax.swing.event.InternalFrameEvent evt) {
    }
    public void internalFrameOpened(javax.swing.event.InternalFrameEvent evt) {
    }
});
}//GEN-LAST:event_btn3ActionPerformed

private void btn4ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn4ActionPerformed
// TODO add your handling code here:
     jLabel1.setVisible(false);
    btn1.setVisible(false);
    
    
    btn2.setVisible(false);
    btn3.setVisible(false);
    btn6.setVisible(false);
   
    btn4.setVisible(false);
    btn5.setVisible(false);
    
    jLabel2 = new javax.swing.JLabel();

    jLabel2.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Imagenes/MinilinkTop.JPG"))); // NOI18N

    getContentPane().add(jLabel2);
    jLabel2.setBounds(60, 0, 1030, 300);
    jInternalFrame1 = new javax.swing.JInternalFrame();
    jInternalFrame1.setTitle("Informaciones adicionales");
  
    jInternalFrame1.setResizable(false);
    jInternalFrame1.setClosable(true);
    jInternalFrame1.setVisible(true);
    getContentPane().add(jInternalFrame1);
    jInternalFrame1.setBounds(50, 280, 1000, 400);
    
   jInternalFrame1.addInternalFrameListener(new javax.swing.event.InternalFrameListener() {
    public void internalFrameActivated(javax.swing.event.InternalFrameEvent evt) {
    }
    public void internalFrameClosed(javax.swing.event.InternalFrameEvent evt) {
        jInternalFrame1InternalFrameClosed(evt);
    }
    public void internalFrameClosing(javax.swing.event.InternalFrameEvent evt) {
    }
    public void internalFrameDeactivated(javax.swing.event.InternalFrameEvent evt) {
    }
    public void internalFrameDeiconified(javax.swing.event.InternalFrameEvent evt) {
    }
    public void internalFrameIconified(javax.swing.event.InternalFrameEvent evt) {
    }
    public void internalFrameOpened(javax.swing.event.InternalFrameEvent evt) {
    }
});
}//GEN-LAST:event_btn4ActionPerformed

private void btn5ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn5ActionPerformed
// TODO add your handling code here:
     jLabel1.setVisible(false);
    btn1.setVisible(false);
    
    
    btn2.setVisible(false);
    btn3.setVisible(false);
    btn6.setVisible(false);
   
    btn4.setVisible(false);
    btn5.setVisible(false);
    
    jLabel2 = new javax.swing.JLabel();

    jLabel2.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Imagenes/MinilinkTop.JPG"))); // NOI18N

    getContentPane().add(jLabel2);
    jLabel2.setBounds(60, 0, 1030, 300);
    jInternalFrame1 = new javax.swing.JInternalFrame();
    jInternalFrame1.setTitle("Informaciones adicionales");
  
    jInternalFrame1.setResizable(false);
    jInternalFrame1.setClosable(true);
    jInternalFrame1.setVisible(true);
    getContentPane().add(jInternalFrame1);
    jInternalFrame1.setBounds(50, 280, 1000, 400);
    
   jInternalFrame1.addInternalFrameListener(new javax.swing.event.InternalFrameListener() {
    public void internalFrameActivated(javax.swing.event.InternalFrameEvent evt) {
    }
    public void internalFrameClosed(javax.swing.event.InternalFrameEvent evt) {
        jInternalFrame1InternalFrameClosed(evt);
    }
    public void internalFrameClosing(javax.swing.event.InternalFrameEvent evt) {
    }
    public void internalFrameDeactivated(javax.swing.event.InternalFrameEvent evt) {
    }
    public void internalFrameDeiconified(javax.swing.event.InternalFrameEvent evt) {
    }
    public void internalFrameIconified(javax.swing.event.InternalFrameEvent evt) {
    }
    public void internalFrameOpened(javax.swing.event.InternalFrameEvent evt) {
    }
});
}//GEN-LAST:event_btn5ActionPerformed

private void btn6ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn6ActionPerformed
// TODO add your handling code here:
     jLabel1.setVisible(false);
    btn1.setVisible(false);
    
    
    btn2.setVisible(false);
    btn3.setVisible(false);
    btn6.setVisible(false);
   
    btn4.setVisible(false);
    btn5.setVisible(false);
    
    jLabel2 = new javax.swing.JLabel();

    jLabel2.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Imagenes/MinilinkTop.JPG"))); // NOI18N

    getContentPane().add(jLabel2);
    jLabel2.setBounds(60, 0, 1030, 300);
    jInternalFrame1 = new javax.swing.JInternalFrame();
    jInternalFrame1.setTitle("Informaciones adicionales");
  
    jInternalFrame1.setResizable(false);
    jInternalFrame1.setClosable(true);
    jInternalFrame1.setVisible(true);
    getContentPane().add(jInternalFrame1);
    jInternalFrame1.setBounds(50, 280, 1000, 400);
    
   jInternalFrame1.addInternalFrameListener(new javax.swing.event.InternalFrameListener() {
    public void internalFrameActivated(javax.swing.event.InternalFrameEvent evt) {
    }
    public void internalFrameClosed(javax.swing.event.InternalFrameEvent evt) {
        jInternalFrame1InternalFrameClosed(evt);
    }
    public void internalFrameClosing(javax.swing.event.InternalFrameEvent evt) {
    }
    public void internalFrameDeactivated(javax.swing.event.InternalFrameEvent evt) {
    }
    public void internalFrameDeiconified(javax.swing.event.InternalFrameEvent evt) {
    }
    public void internalFrameIconified(javax.swing.event.InternalFrameEvent evt) {
    }
    public void internalFrameOpened(javax.swing.event.InternalFrameEvent evt) {
    }
});
}//GEN-LAST:event_btn6ActionPerformed

private void jInternalFrame1InternalFrameClosed(javax.swing.event.InternalFrameEvent evt) {
// TODO add your handling code here:
    jLabel2.setVisible(false);
    jLabel1.setVisible(true);
    btn1.setVisible(true);
   
    
    btn1.setVisible(true);
    btn3.setVisible(true);
    btn6.setVisible(true);
    
    btn4.setVisible(true);
    btn5.setVisible(true);
     
}   
    /**
    * @param args the command line arguments
    */
    public static void main(String args[]) {
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new MapaOComerciales().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btn1;
    private javax.swing.JButton btn2;
    private javax.swing.JButton btn3;
    private javax.swing.JButton btn4;
    private javax.swing.JButton btn5;
    private javax.swing.JButton btn6;
    private javax.swing.JLabel jLabel1;
    // End of variables declaration//GEN-END:variables

}
