package mapa_cubacel;




//import Mapa.*;
import java.awt.BorderLayout;
import java.awt.Container;
import java.awt.Dimension;
import java.awt.Event;
import java.awt.event.MouseAdapter;
import java.awt.event.MouseEvent;
import javax.swing.JApplet;
import javax.swing.JDialog;

/*
 * MyFrame.java
 *
 * Created on September 10, 2011, 8:14 AM
 */
import javax.swing.JFrame;
import javax.swing.JInternalFrame;
import javax.swing.JLabel;
import javax.swing.JOptionPane;
import javax.swing.JScrollPane;
import javax.swing.JTable;
import javax.swing.JTextArea;
import javax.swing.table.DefaultTableModel;
import mapa_cubacel.Informacion;
import mapa_cubacel.Menu_Select;
import mapa_cubacel.Reconocimiento;
//import org.jvnet.substance.*;
//import org.jvnet.substance.watermark.*;



/**
 *
 * @author  heidy.capote
 */
class Principal extends javax.swing.JFrame {
private JLabel jLabela, jLabelb, jLabelc, jLabeld;
private JLabel labela, labelb, labelc, labeld,label;
private int saber,tipo,id;
private JTable tabla;
JInternalFrame jInternalFrame2;
JDialog dg;
    /** Creates new form MyFrame */
    public Principal() {
        initComponents();
    }

    /** This method is called from within the constructor to
     * initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is
     * always regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        MSoftCamaguey = new javax.swing.JButton();
        jLabel2 = new javax.swing.JLabel();
        MsoftHabana = new javax.swing.JButton();
        jLabel3 = new javax.swing.JLabel();
        MsofJaguey = new javax.swing.JButton();
        jLabel4 = new javax.swing.JLabel();
        BSCPanorama = new javax.swing.JButton();
        BSCCubanacan = new javax.swing.JButton();
        BSCHolguin = new javax.swing.JButton();
        BSCVClara = new javax.swing.JButton();
        BSCZTE = new javax.swing.JButton();
        BSCJaguey = new javax.swing.JButton();
        jLabel5 = new javax.swing.JLabel();
        jLabel6 = new javax.swing.JLabel();
        jLabel7 = new javax.swing.JLabel();
        jLabel8 = new javax.swing.JLabel();
        jLabel9 = new javax.swing.JLabel();
        jLabel10 = new javax.swing.JLabel();
        Opciones = new javax.swing.JButton();
        HlrHuawei = new javax.swing.JButton();
        HlrPanorama = new javax.swing.JButton();
        jLabel11 = new javax.swing.JLabel();
        jLabel12 = new javax.swing.JLabel();
        THolguin = new javax.swing.JButton();
        TLuz = new javax.swing.JButton();
        TAguila = new javax.swing.JButton();
        TVClara = new javax.swing.JButton();
        jLabel13 = new javax.swing.JLabel();
        jLabel14 = new javax.swing.JLabel();
        jLabel15 = new javax.swing.JLabel();
        jLabel16 = new javax.swing.JLabel();
        RedInteligente = new javax.swing.JButton();
        jLabel17 = new javax.swing.JLabel();
        MSCCubanacan = new javax.swing.JButton();
        jLabel18 = new javax.swing.JLabel();
        BSCCamaguey1 = new javax.swing.JButton();
        jLabel19 = new javax.swing.JLabel();
        jInternalFrame1 = new javax.swing.JInternalFrame();
        jLabel1 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setResizable(false);

        MSoftCamaguey.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Img/Nodo1.JPG"))); // NOI18N
        MSoftCamaguey.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                MSoftCamagueyActionPerformed(evt);
            }
        });

        jLabel2.setText("MSoft Cubanacan");

        MsoftHabana.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Img/Nodo1.JPG"))); // NOI18N
        MsoftHabana.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                MsoftHabanaActionPerformed(evt);
            }
        });

        jLabel3.setText("MSC-HLR Cubanacan");

        MsofJaguey.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Img/Nodo1.JPG"))); // NOI18N
        MsofJaguey.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                MsofJagueyActionPerformed(evt);
            }
        });

        jLabel4.setText("MSoft Camaguey");

        BSCPanorama.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Img/BSC.JPG"))); // NOI18N
        BSCPanorama.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                BSCPanoramaActionPerformed(evt);
            }
        });

        BSCCubanacan.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Img/BSC.JPG"))); // NOI18N
        BSCCubanacan.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                BSCCubanacanActionPerformed(evt);
            }
        });

        BSCHolguin.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Img/BSC.JPG"))); // NOI18N
        BSCHolguin.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                BSCHolguinActionPerformed(evt);
            }
        });

        BSCVClara.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Img/BSC.JPG"))); // NOI18N
        BSCVClara.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                BSCVClaraActionPerformed(evt);
            }
        });

        BSCZTE.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Img/BSC.JPG"))); // NOI18N
        BSCZTE.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                BSCZTEActionPerformed(evt);
            }
        });

        BSCJaguey.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Img/BSC.JPG"))); // NOI18N
        BSCJaguey.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                BSCJagueyActionPerformed(evt);
            }
        });

        jLabel5.setText("BSC Cubanacan");

        jLabel6.setText("BSC Panorama");

        jLabel7.setText("BSC VClara");

        jLabel8.setText("BSC ZTE");

        jLabel9.setText("BSC Camaguey");

        jLabel10.setText("BSC Hoguin");

        Opciones.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Img/Menu.JPG"))); // NOI18N
        Opciones.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                OpcionesActionPerformed(evt);
            }
        });

        HlrHuawei.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Img/yy.gif"))); // NOI18N
        HlrHuawei.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                HlrHuaweiActionPerformed(evt);
            }
        });

        HlrPanorama.setBackground(javax.swing.UIManager.getDefaults().getColor("TextArea.inactiveBackground"));
        HlrPanorama.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Img/yy.gif"))); // NOI18N
        HlrPanorama.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                HlrPanoramaActionPerformed(evt);
            }
        });

        jLabel11.setText("HLR Panrama");

        jLabel12.setText("HLR Huawei");

        THolguin.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Img/ball.red.gif"))); // NOI18N
        THolguin.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                THolguinActionPerformed(evt);
            }
        });

        TLuz.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Img/ball.red.gif"))); // NOI18N
        TLuz.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                TLuzActionPerformed(evt);
            }
        });

        TAguila.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Img/ball.red.gif"))); // NOI18N
        TAguila.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                TAguilaActionPerformed(evt);
            }
        });

        TVClara.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Img/ball.red.gif"))); // NOI18N
        TVClara.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                TVClaraActionPerformed(evt);
            }
        });

        jLabel13.setText("Tan. Luz");

        jLabel14.setText("Tan. Aguila");

        jLabel15.setText("Tan.VClara");

        jLabel16.setText("Tan.Holguin");

        RedInteligente.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Img/i.gif"))); // NOI18N
        RedInteligente.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                RedInteligenteActionPerformed(evt);
            }
        });

        jLabel17.setText("Red Inteligente");

        MSCCubanacan.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Img/Nodo1.JPG"))); // NOI18N
        MSCCubanacan.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                MSCCubanacanActionPerformed(evt);
            }
        });

        jLabel18.setFont(new java.awt.Font("Tahoma", 0, 12));
        jLabel18.setText("Msoft Jaguey");

        BSCCamaguey1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Img/BSC.JPG"))); // NOI18N
        BSCCamaguey1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                BSCCamaguey1ActionPerformed(evt);
            }
        });

        jLabel19.setText("BSC Jaguey");

        jLabel1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Img/MapaCuba.jpg"))); // NOI18N

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(170, 170, 170)
                .addComponent(jLabel11, javax.swing.GroupLayout.PREFERRED_SIZE, 80, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(160, 160, 160)
                .addComponent(RedInteligente, javax.swing.GroupLayout.PREFERRED_SIZE, 40, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(10, 10, 10)
                .addComponent(jLabel17, javax.swing.GroupLayout.PREFERRED_SIZE, 100, javax.swing.GroupLayout.PREFERRED_SIZE))
            .addGroup(layout.createSequentialGroup()
                .addGap(92, 92, 92)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(HlrPanorama, javax.swing.GroupLayout.PREFERRED_SIZE, 20, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(10, 10, 10))
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(jLabel6, javax.swing.GroupLayout.PREFERRED_SIZE, 90, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(18, 18, 18)))
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(60, 60, 60)
                        .addComponent(jLabel2, javax.swing.GroupLayout.PREFERRED_SIZE, 100, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(60, 60, 60)
                        .addComponent(MsoftHabana, javax.swing.GroupLayout.PREFERRED_SIZE, 28, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(BSCPanorama, javax.swing.GroupLayout.PREFERRED_SIZE, 28, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(32, 32, 32)
                        .addComponent(BSCCubanacan, javax.swing.GroupLayout.PREFERRED_SIZE, 28, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jLabel5, javax.swing.GroupLayout.PREFERRED_SIZE, 90, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(10, 10, 10)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(layout.createSequentialGroup()
                                .addGap(20, 20, 20)
                                .addComponent(TLuz, javax.swing.GroupLayout.PREFERRED_SIZE, 10, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addComponent(jLabel13))
                        .addGap(29, 29, 29)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(layout.createSequentialGroup()
                                .addGap(20, 20, 20)
                                .addComponent(TAguila, javax.swing.GroupLayout.PREFERRED_SIZE, 10, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addComponent(jLabel14))
                        .addGap(6, 6, 6)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(BSCZTE, javax.swing.GroupLayout.PREFERRED_SIZE, 28, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jLabel8, javax.swing.GroupLayout.PREFERRED_SIZE, 50, javax.swing.GroupLayout.PREFERRED_SIZE))))
                .addComponent(MsofJaguey, javax.swing.GroupLayout.PREFERRED_SIZE, 28, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(2, 2, 2)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel18)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(40, 40, 40)
                        .addComponent(jLabel3, javax.swing.GroupLayout.PREFERRED_SIZE, 120, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(60, 60, 60)
                        .addComponent(MSCCubanacan, javax.swing.GroupLayout.PREFERRED_SIZE, 28, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(20, 20, 20)
                        .addComponent(BSCJaguey, javax.swing.GroupLayout.PREFERRED_SIZE, 28, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(72, 72, 72)
                        .addComponent(BSCVClara, javax.swing.GroupLayout.PREFERRED_SIZE, 28, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addGap(150, 150, 150)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel12, javax.swing.GroupLayout.PREFERRED_SIZE, 70, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(HlrHuawei, javax.swing.GroupLayout.PREFERRED_SIZE, 20, javax.swing.GroupLayout.PREFERRED_SIZE)))
            .addGroup(layout.createSequentialGroup()
                .addGap(410, 410, 410)
                .addComponent(TVClara, javax.swing.GroupLayout.PREFERRED_SIZE, 10, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(20, 20, 20)
                .addComponent(jLabel19)
                .addGap(273, 273, 273)
                .addComponent(jLabel4, javax.swing.GroupLayout.PREFERRED_SIZE, 100, javax.swing.GroupLayout.PREFERRED_SIZE))
            .addGroup(layout.createSequentialGroup()
                .addGap(360, 360, 360)
                .addComponent(jLabel15, javax.swing.GroupLayout.PREFERRED_SIZE, 70, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(340, 340, 340)
                .addComponent(MSoftCamaguey, javax.swing.GroupLayout.PREFERRED_SIZE, 28, javax.swing.GroupLayout.PREFERRED_SIZE))
            .addGroup(layout.createSequentialGroup()
                .addGap(850, 850, 850)
                .addComponent(jLabel16))
            .addGroup(layout.createSequentialGroup()
                .addGap(860, 860, 860)
                .addComponent(THolguin, javax.swing.GroupLayout.PREFERRED_SIZE, 10, javax.swing.GroupLayout.PREFERRED_SIZE))
            .addGroup(layout.createSequentialGroup()
                .addGap(550, 550, 550)
                .addComponent(jLabel9, javax.swing.GroupLayout.PREFERRED_SIZE, 90, javax.swing.GroupLayout.PREFERRED_SIZE))
            .addGroup(layout.createSequentialGroup()
                .addGap(900, 900, 900)
                .addComponent(BSCHolguin, javax.swing.GroupLayout.PREFERRED_SIZE, 28, javax.swing.GroupLayout.PREFERRED_SIZE))
            .addGroup(layout.createSequentialGroup()
                .addGap(10, 10, 10)
                .addComponent(jInternalFrame1, javax.swing.GroupLayout.PREFERRED_SIZE, 180, javax.swing.GroupLayout.PREFERRED_SIZE))
            .addGroup(layout.createSequentialGroup()
                .addGap(580, 580, 580)
                .addComponent(jLabel7, javax.swing.GroupLayout.PREFERRED_SIZE, 60, javax.swing.GroupLayout.PREFERRED_SIZE))
            .addGroup(layout.createSequentialGroup()
                .addGap(650, 650, 650)
                .addComponent(BSCCamaguey1, javax.swing.GroupLayout.PREFERRED_SIZE, 28, javax.swing.GroupLayout.PREFERRED_SIZE))
            .addComponent(Opciones, javax.swing.GroupLayout.PREFERRED_SIZE, 10, javax.swing.GroupLayout.PREFERRED_SIZE)
            .addGroup(layout.createSequentialGroup()
                .addGap(940, 940, 940)
                .addComponent(jLabel10, javax.swing.GroupLayout.PREFERRED_SIZE, 70, javax.swing.GroupLayout.PREFERRED_SIZE))
            .addComponent(jLabel1)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(70, 70, 70)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(layout.createSequentialGroup()
                                .addGap(20, 20, 20)
                                .addComponent(jLabel11))
                            .addComponent(RedInteligente, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jLabel17))
                        .addGap(6, 6, 6)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(HlrPanorama, javax.swing.GroupLayout.PREFERRED_SIZE, 20, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(52, 52, 52)
                                .addComponent(jLabel6))
                            .addGroup(layout.createSequentialGroup()
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                                    .addGroup(layout.createSequentialGroup()
                                        .addComponent(jLabel2)
                                        .addGap(6, 6, 6)
                                        .addComponent(MsoftHabana, javax.swing.GroupLayout.PREFERRED_SIZE, 20, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                            .addGroup(layout.createSequentialGroup()
                                                .addGap(40, 40, 40)
                                                .addComponent(jLabel5)
                                                .addGap(3, 3, 3))
                                            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                                .addComponent(BSCCubanacan, javax.swing.GroupLayout.PREFERRED_SIZE, 17, javax.swing.GroupLayout.PREFERRED_SIZE)
                                                .addGap(13, 13, 13))))
                                    .addComponent(BSCPanorama, javax.swing.GroupLayout.PREFERRED_SIZE, 17, javax.swing.GroupLayout.PREFERRED_SIZE))
                                .addGap(6, 6, 6)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addGroup(layout.createSequentialGroup()
                                        .addComponent(TLuz, javax.swing.GroupLayout.PREFERRED_SIZE, 10, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addComponent(jLabel13))
                                    .addGroup(layout.createSequentialGroup()
                                        .addComponent(TAguila, javax.swing.GroupLayout.PREFERRED_SIZE, 10, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addGap(10, 10, 10)
                                        .addComponent(jLabel14))
                                    .addGroup(layout.createSequentialGroup()
                                        .addComponent(BSCZTE, javax.swing.GroupLayout.PREFERRED_SIZE, 17, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addGap(3, 3, 3)
                                        .addComponent(jLabel8))))
                            .addGroup(layout.createSequentialGroup()
                                .addGap(20, 20, 20)
                                .addComponent(MsofJaguey, javax.swing.GroupLayout.PREFERRED_SIZE, 20, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addGroup(layout.createSequentialGroup()
                                .addGap(10, 10, 10)
                                .addComponent(jLabel18)
                                .addGap(5, 5, 5)
                                .addComponent(jLabel3)
                                .addGap(6, 6, 6)
                                .addComponent(MSCCubanacan, javax.swing.GroupLayout.PREFERRED_SIZE, 20, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(60, 60, 60)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(BSCJaguey, javax.swing.GroupLayout.PREFERRED_SIZE, 17, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(BSCVClara, javax.swing.GroupLayout.PREFERRED_SIZE, 17, javax.swing.GroupLayout.PREFERRED_SIZE)))
                            .addGroup(layout.createSequentialGroup()
                                .addGap(80, 80, 80)
                                .addComponent(jLabel12)
                                .addGap(6, 6, 6)
                                .addComponent(HlrHuawei, javax.swing.GroupLayout.PREFERRED_SIZE, 20, javax.swing.GroupLayout.PREFERRED_SIZE)))
                        .addGap(3, 3, 3)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(layout.createSequentialGroup()
                                .addGap(10, 10, 10)
                                .addComponent(TVClara, javax.swing.GroupLayout.PREFERRED_SIZE, 10, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addComponent(jLabel19)
                            .addComponent(jLabel4))
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel15)
                            .addGroup(layout.createSequentialGroup()
                                .addGap(10, 10, 10)
                                .addComponent(MSoftCamaguey, javax.swing.GroupLayout.PREFERRED_SIZE, 20, javax.swing.GroupLayout.PREFERRED_SIZE)))
                        .addGap(40, 40, 40)
                        .addComponent(jLabel16)
                        .addGap(16, 16, 16)
                        .addComponent(THolguin, javax.swing.GroupLayout.PREFERRED_SIZE, 10, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addComponent(jLabel9)
                        .addGap(6, 6, 6)
                        .addComponent(BSCHolguin, javax.swing.GroupLayout.PREFERRED_SIZE, 17, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(33, 33, 33)
                        .addComponent(jInternalFrame1, javax.swing.GroupLayout.PREFERRED_SIZE, 140, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(220, 220, 220)
                        .addComponent(jLabel7))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(380, 380, 380)
                        .addComponent(BSCCamaguey1, javax.swing.GroupLayout.PREFERRED_SIZE, 17, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(480, 480, 480)
                        .addComponent(Opciones, javax.swing.GroupLayout.PREFERRED_SIZE, 80, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(390, 390, 390)
                        .addComponent(jLabel10)))
                .addContainerGap(169, Short.MAX_VALUE))
            .addComponent(jLabel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

private void BSCHolguinActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_BSCHolguinActionPerformed
// TODO add your handling code here:
  id=10;
      Reconocimiento rc=new Reconocimiento(id);//para index detalles del nodo

     Menu_Select mn=new Menu_Select(id);
    
    
                     
}//GEN-LAST:event_BSCHolguinActionPerformed

private void MsoftHabanaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_MsoftHabanaActionPerformed
// TODO add your handling code here:
    id=0;
    Reconocimiento rc=new Reconocimiento(id);//para index detalles del nodo
     Menu_Select mn=new Menu_Select(id);
   
}//GEN-LAST:event_MsoftHabanaActionPerformed

private void BSCPanoramaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_BSCPanoramaActionPerformed
// TODO add your handling code here:
   id=5;
    Reconocimiento rc=new Reconocimiento(id);//para index detalles del nodo
    Menu_Select mn=new Menu_Select(id);   
}//GEN-LAST:event_BSCPanoramaActionPerformed

private void BSCCubanacanActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_BSCCubanacanActionPerformed
// TODO add your handling code here:
      id=6;
      Reconocimiento rc=new Reconocimiento(id);//para index detalles del nodo
     Menu_Select mn=new Menu_Select(id);
}//GEN-LAST:event_BSCCubanacanActionPerformed

private void MSC1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_MSC1ActionPerformed
// TODO add your handling code here:
     id=2;
     Reconocimiento rc=new Reconocimiento(id);//para index detalles del nodo

     Menu_Select mn=new Menu_Select(id);// TODO add your handling code here: 
}//GEN-LAST:event_MSC1ActionPerformed

private void BSCVClaraActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_BSCVClaraActionPerformed
// TODO add your handling code here:
   id=9;
       Reconocimiento rc=new Reconocimiento(id);//para index detalles del nodo
     Menu_Select mn=new Menu_Select(id);    
}//GEN-LAST:event_BSCVClaraActionPerformed

private void BSCZTEActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_BSCZTEActionPerformed
// TODO add your handling code here:
    id=7;
       Reconocimiento rc=new Reconocimiento(id);//para index detalles del nodo
     Menu_Select mn=new Menu_Select(id);
}//GEN-LAST:event_BSCZTEActionPerformed

private void MSoftCamagueyActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_MSoftCamagueyActionPerformed
// TODO add your handling code here:
   
 id=3;
       Reconocimiento rc=new Reconocimiento(id);//para index detalles del nodo
     Menu_Select mn=new Menu_Select(id);
      
}//GEN-LAST:event_MSoftCamagueyActionPerformed

private void BSCJagueyActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_BSCJagueyActionPerformed
// TODO add your handling code here:
     id=8;
       Reconocimiento rc=new Reconocimiento(id);//para index detalles del nodo
     Menu_Select mn=new Menu_Select(id);
}//GEN-LAST:event_BSCJagueyActionPerformed

private void OpcionesActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_OpcionesActionPerformed
// TODO add your handling code here:
    
    id=20;
    
    Menu_Select ms=new Menu_Select(id);
    
   


}//GEN-LAST:event_OpcionesActionPerformed
  
private void HlrPanoramaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_HlrPanoramaActionPerformed
// TODO add your handling code here:
     id=13;
       Reconocimiento rc=new Reconocimiento(id);//para index detalles del nodo
     Menu_Select mn=new Menu_Select(id); 
}//GEN-LAST:event_HlrPanoramaActionPerformed



private void HlrHuaweiActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_HlrHuaweiActionPerformed
// TODO add your handling code here:
     id=15;
       Reconocimiento rc=new Reconocimiento(id);//para index detalles del nodo
     Menu_Select mn=new Menu_Select(id);
}//GEN-LAST:event_HlrHuaweiActionPerformed

private void RedInteligenteActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_RedInteligenteActionPerformed
// TODO add your handling code here:
      id=16;
       Reconocimiento rc=new Reconocimiento(id);//para index detalles del nodo
     Menu_Select mn=new Menu_Select(id);
}//GEN-LAST:event_RedInteligenteActionPerformed

private void TLuzActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_TLuzActionPerformed
// TODO add your handling code here:
     id=17;
       Reconocimiento rc=new Reconocimiento(id);//para index detalles del nodo
     Menu_Select mn=new Menu_Select(id);
    
}//GEN-LAST:event_TLuzActionPerformed

private void TAguilaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_TAguilaActionPerformed
// TODO add your handling code here:
    id=18;
       Reconocimiento rc=new Reconocimiento(id);//para index detalles del nodo
     Menu_Select mn=new Menu_Select(id); 
}//GEN-LAST:event_TAguilaActionPerformed

private void TVClaraActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_TVClaraActionPerformed
// TODO add your handling code here:
    id=19;
       Reconocimiento rc=new Reconocimiento(id);//para index detalles del nodo
     Menu_Select mn=new Menu_Select(id);
}//GEN-LAST:event_TVClaraActionPerformed

private void THolguinActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_THolguinActionPerformed
// TODO add your handling code here:
   id=20;
       Reconocimiento rc=new Reconocimiento(id);//para index detalles del nodo
     Menu_Select mn=new Menu_Select(id);
}//GEN-LAST:event_THolguinActionPerformed

private void BSCCamaguey1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_BSCCamaguey1ActionPerformed
// TODO add your handling code here:
    id=10;
    Reconocimiento rc=new Reconocimiento(id);//para index detalles del nodo
    Menu_Select mn=new Menu_Select(id);
}//GEN-LAST:event_BSCCamaguey1ActionPerformed

private void MsofJagueyActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_MsofJagueyActionPerformed
// TODO add your handling code here:
      id=1;
       Reconocimiento rc=new Reconocimiento(id);//para index detalles del nodo
     Menu_Select mn=new Menu_Select(id);
}//GEN-LAST:event_MsofJagueyActionPerformed

private void MSCCubanacanActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_MSCCubanacanActionPerformed
// TODO add your handling code here:
      id=2;
       Reconocimiento rc=new Reconocimiento(id);//para index detalles del nodo
     Menu_Select mn=new Menu_Select(id);
}//GEN-LAST:event_MSCCubanacanActionPerformed


    /**
    * @param args the command line arguments
    */
    public static void main(String args[]) {
        JFrame.setDefaultLookAndFeelDecorated(true);
    //    SubstanceLookAndFeel.setCurrentTheme("org.jvnet.substance.theme.SubstanceOliveTheme");
       // SubstanceLookAndFeel.setSkin("org.jvnet.substance.skin.MagmaSkin");
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                
                new Principal().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton BSCCamaguey1;
    private javax.swing.JButton BSCCubanacan;
    private javax.swing.JButton BSCHolguin;
    private javax.swing.JButton BSCJaguey;
    private javax.swing.JButton BSCPanorama;
    private javax.swing.JButton BSCVClara;
    private javax.swing.JButton BSCZTE;
    private javax.swing.JButton HlrHuawei;
    private javax.swing.JButton HlrPanorama;
    private javax.swing.JButton MSCCubanacan;
    private javax.swing.JButton MSoftCamaguey;
    private javax.swing.JButton MsofJaguey;
    private javax.swing.JButton MsoftHabana;
    private javax.swing.JButton Opciones;
    private javax.swing.JButton RedInteligente;
    private javax.swing.JButton TAguila;
    private javax.swing.JButton THolguin;
    private javax.swing.JButton TLuz;
    private javax.swing.JButton TVClara;
    private javax.swing.JInternalFrame jInternalFrame1;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel10;
    private javax.swing.JLabel jLabel11;
    private javax.swing.JLabel jLabel12;
    private javax.swing.JLabel jLabel13;
    private javax.swing.JLabel jLabel14;
    private javax.swing.JLabel jLabel15;
    private javax.swing.JLabel jLabel16;
    private javax.swing.JLabel jLabel17;
    private javax.swing.JLabel jLabel18;
    private javax.swing.JLabel jLabel19;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel jLabel9;
    // End of variables declaration//GEN-END:variables

}
public class Sine extends JApplet{
     Principal pc=new Principal();
     public void init(){
        Container cp = getContentPane();
        cp.add(pc);
        /*ciclos.addChangeListener(new ChangeListener(){
          public void stateChanged(ChangeEvent e){
                          senos.setCiclos(((JSlider)e.getSource()).getValue());
                           ((JSlider)e.getSource()).setToolTipText(""+ciclos.getValue());
          }//Ffunc anonima

            
        });*/
        //cp.add(BorderLayout.SOUTH, ciclos);
      }//Ffunc init
   }//Fclass SineWave